foo_ui_columns/config_object.h, foo_ui_columns/config_vars.cpp, foo_ui_columns/config_vars.h, foo_ui_columns/fcl_layout.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters
Resolves https://github.com/reupen/columns_ui/issues/53
This is to allow other components access to the setting.
=> Make settings::allow_locked_panel_resizing a config_object

README.md, foo_ui_columns/foo_ui_columns.vcxproj
For better compatibility with Visual Studio 2017 15.5.
=> Update Windows SDK to version 10.0.16299.0

CHANGELOG.md, foo_ui_columns/commandline.cpp, foo_ui_columns/fcl.cpp, foo_ui_columns/fcl.h, foo_ui_columns/stdafx.h
Resolves https://github.com/reupen/columns_ui/issues/47
=> Add CLI commands for exporting FCL files

foo_ui_columns/NG Playlist/ng_playlist.cpp, foo_ui_columns/NG Playlist/ng_playlist.h, foo_ui_columns/NG Playlist/ng_playlist_clipboard.cpp, foo_ui_columns/filter.h, foo_ui_columns/filter_menu.cpp, foo_ui_columns/playlist_switcher_shortcut_menu.cpp, foo_ui_columns/playlist_switcher_v2.h, foo_ui_columns/playlist_view_msgproc.cpp
=> Improve NG playlist behaviour when right-clicking in empty space

foo_ui_columns/callbacks.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/main_window.cpp, foo_ui_columns/main_window.h, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/notification_area.cpp, foo_ui_columns/notification_area.h, foo_ui_columns/tab_notification_area.cpp, foo_ui_columns/user_interface_impl.cpp
Also strictly enforces a Windows 7 SP1 or newer OS requirement.
=> Tidy up user_interface implementation and update foobar2000 SDK

foo_ui_columns/layout.cpp, foo_ui_columns/layout.h
Mostly indentation-related changes.
=> Tidy live editing context menu code slightly

foo_ui_columns/drop_down_list_toolbar.h
=> Fix mouse-wheel scrolling in drop-down list toolbars

CHANGELOG.md, README.md
Also adds a note to the change log to say Visual Studio 2017 15.8 is now being used.
=> Update required Visual Studio version to 2017 15.8 in README

foo_ui_columns/fcl.cpp, foo_ui_columns/fcl_layout.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/filter.h, foo_ui_columns/filter_fcl.cpp, foo_ui_columns/filter_search_bar.cpp, foo_ui_columns/filter_search_bar.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters
Resolves #19 
This:
- adds various Filter panel and toolbar FCL data sets so that Filter configuration is included in FCL files
- changes the layout and toolbar FCL data set priorities so that they are imported last (or nearly last)
=> Include Filter configuration in FCL files

foo_ui_columns/item_details.cpp, foo_ui_columns/item_details_text.cpp, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp, foo_ui_columns/status_pane.cpp, foo_ui_columns/status_pane.h, foo_ui_columns/status_pane_msgproc.cpp
This makes a few more text padding adjustments and makes sure text padding is DPI aware in those places.
=> Make further text padding adjustments

CHANGELOG.md
This adds a missing item and updates the PR links.
=> Update v1.1.0-beta.1 change log

foo_ui_columns/buttons_config_droptarget.cpp, foo_ui_columns/ng_playlist/ng_playlist_droptarget.cpp, foo_ui_columns/playlist_switcher_drop_target.cpp, foo_ui_columns/version.cpp
This updates ui_helpers to pick up various fixes in the list view hit testing logic.
=> Fix inability to click between list view items

foo_ui_columns/config_columns_v2.cpp, foo_ui_columns/config_host.cpp, foo_ui_columns/config_host.h, foo_ui_columns/fcl.cpp, foo_ui_columns/item_details_config.cpp, foo_ui_columns/setup_dialog.cpp
This is to reduce our dependence on foobar2000_sdk_helpers.
=> Replace uses of uCreateDialog with CreateDialogParam

foo_ui_columns/item_properties.cpp
The foobar2000 1.5 SDK clarified that `track_property_provider_v4` is thread-safe while older versions of the interface are not.
Hence, this restricts track property multi-threading to only `track_property_provider_v4`.
=> Restrict Item properties track property multi-threading

foo_ui_columns/list_view_panel.h, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp
This updates ui_helpers where list view rendering is now done by a separate renderer class.
As a result, the playlist view rendering code has also been moved to a renderer class.
=> Update ui_helpers and add playlist view rendering class

CHANGELOG.md, foo_ui_columns/tab_layout.cpp, foo_ui_columns/tab_layout.h
This further refactors and tidies up code related to the layout tree in layout preferences.
=> Further refactor layout preferences tree-related code

CHANGELOG.md
reupen/yuo.be#1
This was previously missed.
=> Add foobar2000 1.3 support removal to 1.3.0-beta.1 changelog

foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/artwork_helpers.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/functional.h, foo_ui_columns/gdiplus.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/stdafx.h, foo_ui_columns/tab_layout.cpp
This replaces uses of `pfc::map_t` and `pfc::chain_list_v2_t` with alternatives from the standard library.
=> Replace uses of pfc::map_t and pfc::chain_list_v2_t

CHANGELOG.md
This updates the change log for version 1.4.0-beta.1.
=> Add change log for version 1.4.0-beta.1

foo_ui_columns/buttons_config_droptarget.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/filter_items.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist_droptarget.cpp
This updates mmh and fbh, and makes changes required for the updated `mmh::Permutation` class.
=> Update mmh and fbh

foo_ui_columns/filter_search_bar.cpp
=> Use search_filter_manager_v2

foo_ui_columns/item_details_text.cpp
#321
This fixes a regression in #323 which broke centre- and right-alignment in Item details when word wrapping was on.
=> Fix Item details horizontal alignment when word wrapping is on

README.md
This updates the instructions for downloading development versions in the README following changes in the Azure Pipelines UI.
=> Update development version download instructions in README

CHANGELOG.md
This updates the foobar2000 and pfc submodules to bring in changes from foobar2000 SDK 2021-02-23.
=> Update to foobar2000 SDK 2021-02-23

foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_helpers.cpp
This makes a few small clean-ups to the artwork panel code (largely deleting commented out code).
It also updates submodules.
=> Tidy up artwork panel code slightly

CHANGELOG.md
This adds the change log for the upcoming 1.7.0-beta.1 release.
=> Update change log for version 1.7.0-beta.1

foo_ui_columns/drop_down_list_toolbar.h
...thus bringing it on par with the Default UI
=> Add colour support to DropDownListToolbar

CHANGELOG.md
This adds entries for #389 and #390 to the change log.
=> Update change log with contributed PRs

CHANGELOG.md, foo_ui_columns/config_appearance.cpp, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/rebar.cpp, foo_ui_columns/rebar.h, foo_ui_columns/status_pane.cpp, foo_ui_columns/status_pane_msgproc.cpp
This adds support for the dark mode to the status pane and improves the toolbars dark mode.
=> Improve status pane and toolbars dark mode

CHANGELOG.md, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/helpers.cpp, foo_ui_columns/helpers.h, foo_ui_columns/layout.h, foo_ui_columns/main_window.cpp, foo_ui_columns/mw_drop_target.cpp, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/splitter.cpp, foo_ui_columns/splitter.h, foo_ui_columns/splitter_panel_container.cpp, foo_ui_columns/status_bar.cpp, foo_ui_columns/status_bar_font_client.cpp, foo_ui_columns/status_pane.cpp, foo_ui_columns/user_interface_impl.cpp, foo_ui_columns/volume.h
This adds dark mode support to the horizontal and vertical splitters, and tweaks the volume toolbar dark mode slightly.
=> Improve splitter and volume toolbar dark modes

CHANGELOG.md, foo_ui_columns/helpers.cpp, foo_ui_columns/helpers.h, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/splitter.h, foo_ui_columns/splitter_panel_container.cpp, foo_ui_columns/splitter_window.cpp, foo_ui_columns/volume.h
This:
- makes panel captions scale with the system DPI setting
- fixes the incorrect positioning of text in vertical panel captions
- makes the status bar pop-up volume bar scale with the system DPI setting
=> Fix DPI scaling of panel captions and pop-up volume bar

.github/workflows/build.yml, README.md, foo_ui_columns/dark_mode_tabs.cpp, foo_ui_columns/stdafx.h
This gets Clang compilation working again (albeit with a couple of workarounds).
=> Fix Clang compilation

foo_ui_columns/buttons.cpp, foo_ui_columns/buttons_config_param.cpp, foo_ui_columns/config_columns_v2.cpp, foo_ui_columns/config_defaults.cpp, foo_ui_columns/config_filter.cpp, foo_ui_columns/filter_search_bar.cpp, foo_ui_columns/item_details_config.cpp, foo_ui_columns/ng_playlist/ng_playlist_config.cpp, foo_ui_columns/playlist_search.cpp, foo_ui_columns/playlist_switcher_shortcut_menu.cpp, foo_ui_columns/playlist_tabs_wndproc.cpp, foo_ui_columns/tab_global.cpp, foo_ui_columns/tab_layout.cpp, foo_ui_columns/tab_main.cpp, foo_ui_columns/tab_notification_area.cpp, foo_ui_columns/tab_playlist_dd.cpp, foo_ui_columns/tab_playlist_swticher.cpp, foo_ui_columns/tab_pview_artwork.cpp, foo_ui_columns/tab_status.cpp
This updates the Columns UI SDK and removes uses of certain legacy helper functions and classes.
=> Remove uses of some legacy helpers

.prettierrc.json, .remarkrc.json, CHANGELOG.md, CONTRIBUTING.md, README.md
This reformats all Markdown files for consistency, and adds some Markdown linting and formatting configuration files.
=> Reformat Markdown files

.gitignore, .pre-commit-config.yaml, .prettierrc.json, .remarkrc.json, CONTRIBUTING.md, COPYING.LESSER, README.md, foo_ui_columns/.clang-format, foo_ui_columns/.clang-tidy, foo_ui_columns/layout_config.cpp, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/ng_playlist/ng_playlist_callbacks.cpp, foo_ui_columns/splitter.cpp, foo_ui_columns/splitter.h, foo_ui_columns/splitter_window.cpp, foo_ui_columns/splitter_window_wndproc.cpp, foo_ui_columns/system_appearance_manager.cpp, foo_ui_columns/system_appearance_manager.h, foo_ui_columns/tab_main.cpp, scripts/versioning.psm1, vcpkg.json
This adds a [pre-commit](https://pre-commit.com/) configuration to ensure source and other text files are formatted on commit.
=> Add pre-commit configuration

CHANGELOG.md, foo_ui_columns/foo_ui_columns.rc
This fixes multiple clipped text labels in playlist view preferences.
=> Fix various truncated labels in playlist view preferences

CHANGELOG.md
This updates the foobar2000 SDK to version 2022-08-29.
=> Update to foobar2000 2.0 SDK 2022-08-29

CHANGELOG.md, foo_ui_columns/filter.h, foo_ui_columns/filter_items.cpp
This improves the performance of the Filter panel under foobar2000 2.0.
=> Improve performance of Filter panels in foobar2000 2.0

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h
This adds foobar2000 2.0 optimisations for:
- playlist view grouping
- sorting by a column in the playlist view
=> Optimise playlist view grouping and sorting in foobar2000 2.0

CHANGELOG.md, foo_ui_columns/item_properties.cpp, foo_ui_columns/pch.h
This improves the performance of the Item properties panel when using foobar2000 2.0.
=> Improve Item properties performance in foobar2000 2.0

CHANGELOG.md
This updates the change log in advance of a new release.
=> Update change log for version 2.0.0-alpha.2

CHANGELOG.md
This adds an entry for #594 to the change log.
=> Update change log for 2.0.0-alpha.2

foo_ui_columns/dark_mode.cpp
Ref: https://hydrogenaud.io/index.php/topic,28647.msg1023999.html#msg1023999
=> Update max Windows 11 version for dark mode menus

CHANGELOG.md, foo_ui_columns/main_window.cpp, foo_ui_columns/rebar.cpp, foo_ui_columns/rebar.h
Resolves #749
This resolves some temporary visual glitches that happened when toggling the Show toolbars option.
=> Resolve glitches when toggling Show toolbars

CHANGELOG.md, foo_ui_columns/buttons.cpp
This:
- cleans up the buttons toolbar window procedure a bit
- adds dark mode support to buttons toolbar tooltips
=> Add dark mode support to buttons toolbar tooltips 

CHANGELOG.md, foo_ui_columns/status_bar.cpp
This updates ui_helpers to pick up some list view updates where tooltip text is now rendered using DirectWrite.
The positioning of centre- and right-aligned tooltips was also improved.
=> Render list view tooltip text using DirectWrite

CHANGELOG.md, foo_ui_columns/status_bar.cpp, foo_ui_columns/status_pane.cpp, foo_ui_columns/status_pane.h, foo_ui_columns/status_pane_msgproc.cpp
This makes the status pane render text using DirectWrite instead of Uniscribe.
=> Migrate status pane to DirectWrite

CHANGELOG.md, foo_ui_columns/filter.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp
Resolves #930 
This updates ui_helpers to get list view (such as the playlist view, Filter panel and Item properties) column titles rendered using DirectWrite.
=> Render list view header text using DirectWrite

CHANGELOG.md, foo_ui_columns/font_manager_v3.cpp
This incorporates a few small tweaks to the font API in the Columns UI SDK.
=> Incorporate minor font API SDK updates

foo_ui_columns/splitter.cpp, foo_ui_columns/splitter.h, foo_ui_columns/splitter_panel.cpp, foo_ui_columns/splitter_panel_container.cpp, foo_ui_columns/splitter_window.cpp, foo_ui_columns/splitter_window_wndproc.cpp
Small bit of modernisation ahead of another change.
=> Use std::vector for FlatSplitterPanel child panel list

CHANGELOG.md
This clarifies the wording in the change log slightly.
=> Update 3.1.0 alpha 3 change log
