foo_ui_columns/config_vars.cpp
Avoids unexpected side effects when downgrading the component.
=> Re-add legacy colour and font setting import status config variable

.clang-format, vc15/columns_ui-public.sln
Sets the tab width to 4 as even though there are no tabs in this repository, ReSharper C++ uses the value when viewing files (headers etc.) that contain tabs.
Also adds  .clang-format and CONTRIBUTING.md to the solution..
=> Update solution and .clang-format tab width

.clang-format, foo_ui_columns/config_layout.cpp
Resolves #52
Improves how copying and pasting panels in the layout preferences page works. Additional data can now be stored in splitter items using the new uie::splitter_item_full_v3_t class in the SDK.
This work will also make it possible to use the Windows clipboard for copying and pasting panels.
=> Add support for storing additional data in splitter items

CHANGELOG.md, foo_ui_columns/file_info_reader.cpp, foo_ui_columns/file_info_reader.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details.h, foo_ui_columns/menubar.cpp, foo_ui_columns/stdafx.h, vc15/columns_ui-public.sln
Resolves #68
This makes the Item details panel load full file info (including large fields such as lyrics) when a selected item is being displayed. (Playing items already showed full file info.)
=> Always load full file info in Item details panel

CHANGELOG.md, foo_ui_columns/volume.h
Corrects the odd calculation that was previously being used for the volume bar scale.
=> Correct the volume bar scale

CHANGELOG.md, foo_ui_columns/drop_down_list_toolbar.h, foo_ui_columns/dsp_preset.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/order_dropdown.cpp, foo_ui_columns/output_device.cpp, foo_ui_columns/panel_menu_item.h, foo_ui_columns/replaygain_mode.cpp
Adds items to the context menus for the DSP preset and ReplayGain mode toolbars to open the DSP Manager and Playback preference pages respectively.
=> Add context menu item to open preferences in certain toolbars

CHANGELOG.md, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/rebar.cpp, foo_ui_columns/rebar.h, foo_ui_columns/rebar_band.cpp, foo_ui_columns/rebar_band.h
This fixes some misbehaviour (including a crash bug) in the toolbars due to the difference in behaviour of the RebarBandInfo copy and move constructors (and also the assignment operators).
Some more work is needed to move the run-time data out of RebarBandInfo but these changes will address the problems encountered.
=> Fix toolbars misbehaviour

CHANGELOG.md, foo_ui_columns/component_impl.cpp, foo_ui_columns/volume.h
Fixes misbehaviour when using the mouse wheel to change the volume using the volume bar, and the volume bar misreporting the current volume in some cases.
This was due to an incorrect calculation being used when converting a volume to a volume bar position.
=> Fix volume bar misbehaviour

foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties.h
Resolves #138
This makes the column widths have an associated DPI, so that they are restored correctly if the DPI changes (between foobar2000 launches) and also so that the default column widths are scaled appropriately.
=> Improve Item properties column-width DPI handling

README.md, appveyor.yml, foo_ui_columns/stdafx.h
This:
- adds range-v3 as a dependency
- adds an include for a helper header added to https://github.com/reupen/pfc that adds basic range-based for support to `pfc::list_t<>` and `pfc::array_t<>`
=> Add range-v3 as a dependency and add range-based for helper

foo_ui_columns/rebar.cpp, foo_ui_columns/rebar.h
For some reason the z-order is getting messed up when bands are initially added to the rebar.
This isn't the nicest of fixes, but is the only reliable one I could find that covers reordering and adding bands at run-time as well.
=> Fix tab order in the toolbars

foo_ui_columns/splitter_window.cpp
This corrects the tab order in horizontal and vertical splitters after reordering panels directly in the main window (by right-clicking on panel captions and using the Move up and Move down commands).
=> Correct tab order in splitters after reordering panels

foo_ui_columns/status_pane.cpp
This re-adds the colon mistakenly removed from after the Playing and Paused text labels in the status pane.
=> Re-add colon to status pane 'Playing' and 'Paused' text

CHANGELOG.md, foo_ui_columns/component_impl.cpp
This improves list view scrolling behaviour when scrolling to partially obscured items (e.g. when clicking on the item at the top of the playlist view when it is only partially visible).
=> Improve list view scrolling behaviour

CHANGELOG.md, README.md, foo_ui_columns/foo_ui_columns.vcxproj
This:
- updates the foobar2000 SDK to version 2018-10-11 (was apparently missed)
- updates the Windows SDK to version 10.0.17763.0 
- removes /FAcs from the compiler options
- removes /MAP from the linker options
=> Update dependencies and project settings

README.md, appveyor.yml, foo_ui_columns/drop_down_list_toolbar.h, foo_ui_columns/helpers.cpp
Resolves #91 
This:
- fixes a C++ conformity problem preventing compilation under Clang
- fixes a C++ conformity problem preventing compilation under Visual Studio 2019
- removes the usage of a Visual Studio feature allowing the conversion of stateless lambdas to __stdcall function pointers, as this is not supported by Clang
- adds Clang and Visual Studio 2019 Preview builds to AppVeyor
=> Restore ability to compile using Clang

CHANGELOG.md
This makes the height of the playlist view and other list view column titles vary with the configured vertical item padding.
It also preserves the scroll position in list views when adjusting certain settings (such as vertical item padding).
=> Make list view header height vary with vertical item padding setting

foo_ui_columns/foo_ui_columns.vcxproj
The missing semicolon was causing an RC1107 error when attempting to use the resource editor in Visual Studio.
=> Add missing trailing semicolon to include directories

azure/job-build.yml, azure/pipeline.yml
This:
- splits the config into two jobs as this seems to be the only way to get each matrix line reported separately on GitHub
- removes the install Vcpkg step as Vcpkg is now pre-installed in the VS 2019 Azure Pipelines image
- gets the LLVM build running again (but not working, there's now a `/SUBSYSTEM:WINDOWS: no such file or directory` error from `llvm-lib.exe`)
=> Update Azure Pipelines configuration

foo_ui_columns/filter.cpp, foo_ui_columns/filter.h, foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties.h, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/playlist_switcher_v2.h
This updates ui_helpers to move handling of built-in character-based keyboard shortcuts to WM_KEYDOWN rather than WM_CHAR in list views.
This is to prevent double-handling if the same combination is assigned to a foobar2000 keyboard shortcut and the foobar2000 keyboard shortcut handler uses a modal message loop.
=> Improve list view keyboard shortcut handling

azure/job-build.yml, azure/pipeline.yml
This makes a few changes (primarily disabling the use of llvm-lib) that get the Clang build working again in the CI build.
VS 2019 16.2.0 will come with native support for LLVM, so we may wish to switch to that later on.
=> Fix Clang build on Azure Pipelines

foo_ui_columns/config_filter.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/filter.h, foo_ui_columns/filter_config_var.cpp, foo_ui_columns/filter_config_var.h, foo_ui_columns/filter_search_bar.cpp, foo_ui_columns/filter_utils.h, foo_ui_columns/foo_ui_columns.rc, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/resource.h
Resolves #171
This adds a new 'Reverse order' setting alongside the existing settings for controlling the sorting behaviour when tracks are added to a playlist from the Filter panel.
=> Allow reverse sorting of Filter selection when added to a playlist

CHANGELOG.md
This updates ui_helpers to fix a bug where text copied in e.g. the Item properties panel could be corrupted. The bug was fixed in reupen/ui_helpers#24 (thanks to @Seraphin-).
=> Fix corruption of copied text in list views

foo_ui_columns/callbacks_config.cpp, foo_ui_columns/fcl_layout.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/get_msg_hook.cpp, foo_ui_columns/get_msg_hook.h, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details.h, foo_ui_columns/item_details_config.cpp, foo_ui_columns/item_details_font.cpp, foo_ui_columns/item_details_text.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties.h, foo_ui_columns/item_properties_config.cpp, foo_ui_columns/item_properties_config_list_view.cpp, foo_ui_columns/layout.cpp, foo_ui_columns/layout.h, foo_ui_columns/layout_config.cpp, foo_ui_columns/main_window.cpp, foo_ui_columns/menu_mnemonics.h, foo_ui_columns/menubar.cpp, foo_ui_columns/mw_drop_target.cpp, foo_ui_columns/mw_drop_target.h, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/setup_dialog.cpp, foo_ui_columns/setup_dialog.h, foo_ui_columns/tab_layout.cpp
There is a [documented naming convention to use UpperCamelCase for class names](https://github.com/reupen/columns_ui/blob/master/CONTRIBUTING.md). 
However, many existing class names are non-compliant. This renames several existing class names to make them compliant.
=> Use UpperCamelCase for class names (part 3)

foo_ui_columns/artwork.cpp, foo_ui_columns/buttons_stock.cpp, foo_ui_columns/colours_manager_data.cpp, foo_ui_columns/colours_manager_data.h, foo_ui_columns/config_appearance.cpp, foo_ui_columns/config_columns_v2.cpp, foo_ui_columns/fcl.cpp, foo_ui_columns/fcl_colours.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/fonts_manager_data.cpp, foo_ui_columns/fonts_manager_data.h, foo_ui_columns/item_details.h, foo_ui_columns/item_details_font.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties.h, foo_ui_columns/main_window.cpp, foo_ui_columns/menu_helpers.cpp, foo_ui_columns/menu_helpers.h, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist_droptarget.cpp, foo_ui_columns/playlist_switcher.cpp, foo_ui_columns/prefs_utils.cpp, foo_ui_columns/prefs_utils.h, foo_ui_columns/tab_display2.cpp, foo_ui_columns/tab_layout.cpp, foo_ui_columns/tab_layout.h, foo_ui_columns/tab_pview_artwork.cpp, foo_ui_columns/tab_status.cpp
There is a [documented naming convention to use UpperCamelCase for class names and other custom types](https://github.com/reupen/columns_ui/blob/master/CONTRIBUTING.md). 
However, many existing class names are non-compliant. This renames several existing class names to make them compliant.
=> Use UpperCamelCase for class names (part 7)

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist_callbacks.cpp, foo_ui_columns/version.cpp
This uses a more optimised path when all items are being removed from the active playlist.
Flickering is also avoided in this case by some changes in ui_helpers and not calling UpdateWindow in this case. 
(We are, perhaps, being too aggressive in calling UpdateWindow in general. However, this targets the main case causing problems.)
=> Optimise replacement of all items in playlist view

foo_ui_columns/rebar.cpp, foo_ui_columns/rebar.h, foo_ui_columns/rebar_band.cpp, foo_ui_columns/rebar_band.h
This fixes a nasty bug where `uie::windor::ptr` instances were escaping into the global `g_cfg_rebar` object, and hence released while the DLL was being unloaded.
This was probably a regression from previous refactoring of related code.
This reorganises things so that such a scenario is impossible.
=> Fix potential crash on foobar2000 exit involving the toolbars

foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties.h, foo_ui_columns/stdafx.h
This significantly improves performance when refreshing the contents of the Item properties panel for large selections.
Refresh times can be as little as 20% of the time taken prior to these changes. This results in a general UI responsiveness improvement, in particular when using library viewers.
Improvements were made partly by removing unneeded processing, and partly by using parallelism.
As a result of these changes, metadata field values are no longer sorted (which was already inconsistent with the rest of foobar2000).
The sort order of track property sections was also corrected.
=> Improve Item properties performance 

foo_ui_columns/config_columns_v2.cpp, foo_ui_columns/config_host.cpp
This fixes a problem where if you were on the playlist view preferences page and had switched away from it to another page, the 'Edit this column' from the playlist view header context menu would not behave correctly.
This is because the code had the expectation that if the preferences dialog had been created, it was visible. However, foobar2000 hides dialogs after switching away from them rather than destroying them. It's noted in a comment elsewhere that this behaviour changed in foobar2000 1.0.
=> Make 'Edit this column' command more robust

foo_ui_columns/buttons.h, foo_ui_columns/buttons_command_picker.cpp, foo_ui_columns/menu_helpers.cpp, foo_ui_columns/menu_helpers.h
This corrects the names of some context menu items in the buttons toolbar.
Some of the menu item enumeration code was also simplified.
=> Correct context menu item names in buttons toolbar

foo_ui_columns/buttons_config_droptarget.cpp
This fixes the incorrect placement of items when reordering buttons in the options dialog for the buttons toolbar.
=> Fix drag-and-drop reordering of buttons in buttons options

foo_ui_columns/filter.cpp
This ensures that the tracks of a Filter panel node are sorted when selected (when sorting is enabled in Filter preferences).
This is so tracks appear sorted in selection viewers.
=> Always sort Filter node tracks on selection

foo_ui_columns/filter.cpp
This changes Filter panel behaviour so that when right-clicking on an item, the selection change is processed normally as it would be when left-clicking.
This means that subsequent Filters are updated, auto-send is triggered and selection viewers are updated.
(Previously, the selection change was effectively ignored, which left the panel in an inconsistent state.)
=> Don't ignore Filter panel selection changes when right-clicking

CHANGELOG.md, foo_ui_columns/item_properties.cpp
This was a result of the changes in #199. `track_property_provider_v3` expects provided `metadb_info_container` objects to be non-null and there is a subtle difference in behaviour between the `metadb_handle::get_info_ref()` overloads.
Now, invalid `metadb_info_container::ptr` objects are avoided completely.
=> Correct handling of null file_info with track_property_provider_v3

foo_ui_columns/buttons_config_param.cpp, foo_ui_columns/filter_items.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_callbacks.cpp, foo_ui_columns/playlist_switcher_v2.cpp
This updates ui_helpers to remove almost all use of `UpdateWindow()` and `RDW_UPDATENOW` in list views to minimise flickering (and similar effects).
(Instead, Windows will send a WM_PAINT message when the message queue is next empty. This has the effect of batching what previously were multiple painting operations.)
=> Remove forced window updating in list views

CHANGELOG.md, foo_ui_columns/version.cpp
This updates ui_helpers to pick up a fix for a bug where it was not possible to double-click on near the top of the viewport in list views.
=> Fix double-clicking on first few visible items in list views

foo_ui_columns/item_properties.cpp, foo_ui_columns/stdafx.h
This fixes some missed multi-threading considerations when refreshing the contents of the Item properties panel.
=> Fix potential crash in Item properties panel

foo_ui_columns/buttons.cpp, foo_ui_columns/buttons.h, foo_ui_columns/buttons_button.cpp, foo_ui_columns/buttons_command_picker.cpp, foo_ui_columns/buttons_config_param.cpp, foo_ui_columns/menu_helpers.cpp, foo_ui_columns/menu_helpers.h
This:
- improves how buttons linked to unknown (e.g. removed) are displayed
- includes the parent node in names of dynamic context menu items in tooltips or button text
- tidies up some of the logic relating to button names
=> Improve naming of menu item-based buttons in buttons toolbar

foo_ui_columns/menu_helpers.cpp, foo_ui_columns/menu_helpers.h, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/prefs_utils.cpp, foo_ui_columns/prefs_utils.h, foo_ui_columns/status_pane_msgproc.cpp, foo_ui_columns/tab_display2.cpp, foo_ui_columns/tab_pview_artwork.cpp, foo_ui_columns/tab_status.cpp
This adds support for dynamic main menu items to the status bar double-click action and the empty space playlist view double-click action.
=> Add support for dynamic main menu items to custom double-click actions

foo_ui_columns/main_window.cpp, foo_ui_columns/main_window.h
This adds a console warning if UI Hacks appears to be installed, due to the problems it is known to cause.
This warning may be made more prominent after version 1.2.0 if it is warranted.
=> Add console warning if UI Hacks appears to be installed

foo_ui_columns/buttons.cpp, foo_ui_columns/buttons_config_param.cpp, foo_ui_columns/fcl.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/item_details_config.cpp, foo_ui_columns/item_properties_config.cpp, foo_ui_columns/ng_playlist/ng_playlist_config.cpp, foo_ui_columns/playlist_manager_utils.cpp, foo_ui_columns/rename_dialog.cpp, foo_ui_columns/rename_dialog.h, foo_ui_columns/tab_layout.cpp, foo_ui_columns/tab_layout.h, foo_ui_columns/vis_spectrum.cpp
This is to reduce our dependence on foobar2000_sdk_helpers.
A shared utility function was also added as a replacement for various naming and renaming dialogs.
=> Replace uses of uDialogBox with DialogBoxParam

README.md
I shamelessly stole(!) your azure pipelines config for my own project earlier and I couldn't help notice you're using an out of date appveyor badge in your readme. This replaces it with a "current" azure one.
=> Update build status badge in readme

foo_ui_columns/tab_layout.cpp, foo_ui_columns/tab_layout.h
Previously, a pointer to each node object was stored in the lParam value of each tree view item.
However, this can be prone to error, and there has existed a very rare crash bug relating to this that is of an unknown cause.
This switches to using an unordered map to map tree item IDs to node objects. This is safer, and also simplifies the overall logic.
(Ignoring white-space changes will make the diff easier to follow.)
=> Rework layout preferences tree item to node object mapping

foo_ui_columns/foo_ui_columns.vcxproj
This switches from having all code analysis rules enabled to just the default rule set.
This is partly due to https://developercommunity.visualstudio.com/content/problem/721337/c-code-analysis-hangs-and-crashes-with-error-msb60.html.
=> Use default code analysis rules

foo_ui_columns/fcl.cpp, foo_ui_columns/filter_fcl.cpp, foo_ui_columns/fonts_manager_data.cpp, foo_ui_columns/item_properties.cpp
Currently, compilation with the latest version of range-v3 is not working.
For Visual Studio, range-v3 now requires the `/experimental:preprocessor` compiler argument. However, specifying this causes an internal compiler error when compiling this project. This will be further investigated separately.
There was also a problem with mixed types when using `ranges::view::iota()`, which was breaking the Clang build (and would probably have also broken the Visual Studio build if it weren't for the other problem). This is fixed here.
=> Partially fix compatibility with latest version of range-v3

README.md, azure/job-build.yml, azure/pipeline.yml, ports/ms-gsl/CONTROL, ports/ms-gsl/portfile.cmake, ports/range-v3/CONTROL, ports/range-v3/portfile.cmake
There was some breakage with the latest version of `range-v3`. This freezes the ports to working versions to get things working again and avoid unexpected breakage in future.
Note: The outstanding problem blocking an upgrade of range-v3 is https://developercommunity.visualstudio.com/content/problem/695652/internal-compiler-error-with-experimentalpreproces.html (which is stated to be fixed in Visual Studio 16.4).
=> Pin ms-gsl and range-v3 ports

.gitmodules
This renames the `common` submodule to `foobar2000`.
The local path remains unchanged.
The repository URLs for the `foobar2000` and `pfc` submodules were also updated.
It should be possible to update local environments by running `git submodule sync` with these changes in place locally.
=> Rename common submodule to foobar2000

CHANGELOG.md
This updates ui_helpers to fix a bug where, when typing the name of an item in a list view to jump to that item, the space key would not jump to matching items due to a bug in how Ctrl+Space was handled.
=> Correct handling of space key in list views

CHANGELOG.md
This updates ui_helpers to pick up various fixes related to the display of ellipses in truncated text that contains colour codes.
=> Fix display of ellipses in truncated text containing colour codes

README.md, azure/job-build.yml, azure/pipeline.yml
This changes the Azure Pipelines configuration to use the Clang toolset as provided by Visual Studio (rather than installing it separately).
It also updates the Clang compilation instructions in the README to do the same.
=> Use Visual Studio-provided LLVM on Azure Pipelines

CHANGELOG.md, foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties.h, foo_ui_columns/item_properties_config.cpp, foo_ui_columns/stdafx.h
This adds better support for track property groups from third-party track property providers that use custom group names.
Properties from such custom groups are now displayed under the correct heading.
The 'Other' section in Item properties option has been renamed 'All other sections' and now controls the display of these custom groups.
(Note that some older versions of Columns UI did display these properties, but they were lumped together under a single 'Other' heading.)
=> Add support for custom property sections to Item properties

CHANGELOG.md, foo_ui_columns/item_properties.cpp
This updates the default Item properties settings so that:
- the playback statistics and any unknown information sections are hidden by default
- metadata field titles use sentence case, in line with the standard information fields
=> Update Item properties default settings

CHANGELOG.md, foo_ui_columns/splitter_utils.cpp
This fixes a bug where, if a panel with a custom title was copied and pasted, the pasted panel would not have the custom title that the original panel had.
=> Fix loss of a panel's custom title when copying and pasting the panel

CHANGELOG.md, foo_ui_columns/tab_layout.cpp, foo_ui_columns/tab_layout.h
This fixes a bug where the expansion state of some nodes in the tree view in Layout preferences was lost when moving a node up or down.
=> Preserve tree view node state in layout preferences when moving items

CHANGELOG.md, foo_ui_columns/tab_layout.cpp, foo_ui_columns/tab_layout.h
This fixes a few bugs in the state management of the layout tree in layout preferences that were leading to misbehaviour and potential crashes.
This happened in particular when reordering panels or removing panels and inserting new ones (after which, the tree items could end up pointing at the wrong nodes).
=> Fix state bugs in layout tree in layout preferences

CHANGELOG.md
This updates ui_helpers to add support for the Ctrl-A keyboard shortcut in list view inline edit controls (on versions of Windows older than Windows 10 1809).
=> Add support for Ctrl-A in list view inline edit controls

CHANGELOG.md, foo_ui_columns/config_host.h, foo_ui_columns/tab_layout.cpp, foo_ui_columns/tab_layout.h
This fixes a bug in layout preferences where, if the selection was cleared (e.g. by selecting a different preset), the panel-specific controls to the right of the tree would stay active when they should be disabled.
=> Correctly disable panel options in layout tree when selection cleared

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist_inline_edit.cpp
This adds support for multiple field values in in-line metadata editing in the playlist view.
This applies to all metadata fields. Multiple values are separated by semicolons.
This also includes a small update to ui_helpers which now detects whether the text has been modified before triggering a save operation.
=> Add support for multiple field values in in-line editing

CHANGELOG.md
This updates ui_helpers to fix an invalid parameter exception when dragging items over a playlist with a title longer than approximately 260 characters.
=> Fix crash when dragging items over playlist with long name

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist_inline_edit.cpp
This fixes various problems with inline metadata editing in the playlist view:
- a crash when setting a field to an empty string
- a crash when saving changes after editing multiple files that had initially differing values
- the unwanted saving of empty values to files (rather than omitting them or removing the field completely)
The behaviour is also changed slightly when encountering files with no loaded metadata – it will always let you attempt to update the file (though this will may well fail).
=> Fix various inline editing bugs in the playlist view

scripts/post-build.ps1, scripts/pre-build.ps1, scripts/versioning.psm1
This alters the post-build script so that, when a tagged release is being built, the version number is included in the file name of the produced component archive.
For example, if the tag `v1.2.0` is being built, the file name of the archive will be `foo_ui_columns-1.2.0.fb2k-component`.
(For other builds, the file name remains `foo_ui_columns.fb2k-component`.)
=> Include version in component archives for releases

CHANGELOG.md, foo_ui_columns/foo_ui_columns.rc, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/resource.h, foo_ui_columns/tab_pview_artwork.cpp
This removes the playlist view ‘Low artwork reader thready priority’ setting as there should be no reason to manually configure the artwork reader thread priority.
It now always uses a low priority.
=> Remove ability to configure playlist view artwork thread priority

foo_ui_columns/artwork.cpp, foo_ui_columns/buttons.h, foo_ui_columns/buttons_config_droptarget.cpp, foo_ui_columns/buttons_config_listview.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/main_window.cpp, foo_ui_columns/main_window.h, foo_ui_columns/mw_drop_target.cpp, foo_ui_columns/mw_drop_target.h, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_clipboard.cpp, foo_ui_columns/ng_playlist/ng_playlist_dropsource.cpp, foo_ui_columns/ng_playlist/ng_playlist_droptarget.cpp, foo_ui_columns/playlist_manager_utils.cpp, foo_ui_columns/playlist_switcher_drop_source.cpp, foo_ui_columns/playlist_switcher_drop_target.cpp, foo_ui_columns/playlist_switcher_v2.cpp, foo_ui_columns/playlist_switcher_v2.h, foo_ui_columns/playlist_tabs.h, foo_ui_columns/playlist_tabs_drop_target.cpp, foo_ui_columns/playlist_tabs_wndproc.cpp, foo_ui_columns/wic.cpp
This replaces uses of `mmh::ComPtr` and `pfc::com_ptr_t` with `wil::com_ptr_t` where it's easy to do so.
=> Use wil::com_ptr_t where possible

foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/filter_search_bar.cpp, foo_ui_columns/filter_search_bar.h, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details.h, foo_ui_columns/item_details_text.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp, foo_ui_columns/splitter.h, foo_ui_columns/splitter_panel_container.cpp, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/splitter_tabs.h, foo_ui_columns/splitter_window.cpp, foo_ui_columns/splitter_window_wndproc.cpp, foo_ui_columns/status_pane.cpp, foo_ui_columns/status_pane.h, foo_ui_columns/status_pane_msgproc.cpp, foo_ui_columns/volume.h
This replaces uses of `gdi_object_t<>::ptr_t` from ui_helpers with equivalents from WIL such as `wil::unique_hbrush` and `wil::shared_hbitmap`.
=> Replace uses of gdi_object_t<>::ptr_t with WIL equivalents 

foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/artwork_helpers.h, foo_ui_columns/buttons.cpp, foo_ui_columns/buttons.h, foo_ui_columns/buttons_command_picker.cpp, foo_ui_columns/buttons_config_droptarget.cpp, foo_ui_columns/buttons_config_param.cpp, foo_ui_columns/commandline.cpp, foo_ui_columns/fcl.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/filter.h, foo_ui_columns/filter_inline_edit.cpp, foo_ui_columns/filter_items.cpp, foo_ui_columns/stdafx.h
This replaces some uses of `pfc::list_t` with standard library alternatives (particularly in cases that it was easy to do so).
=> Replace some uses of pfc::list_t with standard library equivalents

foo_ui_columns/drop_down_list_toolbar.h
Resolves #281
This fixes the inability to vertically scroll the output device, DSP preset and other build-in drop-down list toolbars when they contain a large number of items.
=> Fix inability to scroll drop-down list toolbars with many items

.artifactignore, README.md, azure/job-build.yml, azure/pipeline.yml, scripts/post-build.ps1, scripts/versioning.psm1
This updates the Azure Pipelines configuration to publish release builds as artefacts.
This is to make it easier for changes to be tested prior to them being formally released.
=> Publish development builds on Azure Pipelines

CHANGELOG.md
This updates the foobar2000 and pfc submodules to bring in changes from foobar2000 SDK 2019-12-27.
=> Update to foobar2000 SDK 2019-12-27

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/artwork_helpers.h, foo_ui_columns/config_artwork.cpp, foo_ui_columns/foo_ui_columns.rc, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/legacy_artwork_config.cpp, foo_ui_columns/legacy_artwork_config.h, foo_ui_columns/main_window.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/resource.h
This removes Columns UI’s own artwork settings as:
- they were redundant, as foobar2000’s own settings on the Display preferences page could also be used
- being able to configure artwork sources in two places was causing confusion
The old setting variables are still in place to allow downgrades and to allow users to manually copy settings to Display preferences.
=> Remove artwork source settings

foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp
The artwork reader threads were [implicitly using the process's multi-threaded apartment](https://devblogs.microsoft.com/oldnewthing/20130419-00/?p=4613).
This adds explicit COM initialisation on these threads to avoid any undesirable behaviour from relying on the implicit MTA.
=> Explicitly initialise COM in artwork reader threads

CHANGELOG.md
This clarifies that WebP files will only be loaded if the file extension is explicitly specified (and not when `.*` is used for the file extension). This is presumably as there is a whitelist of file extensions in the foobar2000 core.
=> Add note about WebP support to v1.4.0-beta.1 change log

CHANGELOG.md, foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp
As it turns out, some input components, including built-in ones, try to initialise COM as apartment-threaded ([despite not knowing if the calling thread meets the requirements](https://docs.microsoft.com/en-gb/windows/win32/com/single-threaded-apartments)).
Artwork-reading threads correctly use the multi-threaded apartment. However, this was not compatible with input components trying to use a single-threaded apartment.
This change delays COM initialisation in playlist view artwork threads until after artwork has been read, to try and avoid conflicts. (This appears to work, but there could well still be other problems since the thread doesn't meet the requirements for apartment-threading.)
Explicit COM intialisation is also removed from the artwork view artwork thread, since it doesn't …
=> Work around inputs using COM apartment-threading in artwork threads

CHANGELOG.md, foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp
In some cases (possibly something to do with zip files), the foobar2000 album art API returns zero-length image data.
This ignores any such images, rather than trying to decode them (which, of course, fails).
=> Ignore zero-length artwork images

CHANGELOG.md, foo_ui_columns/buttons_button_image.cpp
This fixes a regression in 09be8e50007a49b24b579cc6885d8c3d427a317b where relative paths of custom images in the buttons toolbar were not resolved.
This may have caused them to fail to load if the current working directory wasn't the one expected.
This only affected image file extensions other than `bmp` and `ico`.
=> Correct loading of images with relative paths in the buttons toolbar

foo_ui_columns/buttons_config_listview.cpp, foo_ui_columns/config_filter.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties_config_list_view.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/playlist_switcher_v2.cpp
This updates ui_helpers following the replacement of some uses of `const pfc::list_base_const_t<uih::ListView::Column>&` with `std::vector<uih::ListView::Column>`.
=> Replace some usages of pfc containers in uih::ListView

CHANGELOG.md, foo_ui_columns/colours_manager_data.cpp
This fixes a bug that was causing custom Album list panel active item frame colours to be omitted from exported FCL files.
This was happening as Album list panel doesn't support turning off the 'Use custom active item frame' option when using custom colours and the exporting code didn't handle this correctly.
=> Always include custom active item frame colours in FCL files

foo_ui_columns/foo_ui_columns.vcxproj
This switches from the old `/experimental:preprocessor` compiler argument to the new `/Zc:preprocessor`.
=> Update compiler options for VS 2019 16.6

foo_ui_columns/filter.h, foo_ui_columns/item_details_text.cpp, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp, foo_ui_columns/playlist_switcher_v2.h, foo_ui_columns/status_pane_msgproc.cpp
#313
This disables tab columns in Item properties and some other panels where title formatting isn't used. This is because it doesn't make sense to enable tab columns without title formatting.
ui_helpers was also updated (where the signature of `text_out_colours_tab()` changed slightly).
=> Disable support for tab columns in some panels

foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/playlist_tabs.h, foo_ui_columns/splitter.h, foo_ui_columns/splitter_panel.cpp, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/splitter_tabs.h
This fixes bugs in the standard splitter panels that caused stale panel configuration data to be copied when a panel was copy and pasted in live editing.
=> Fix stale panel data being copied when copying panels in live editing

foo_ui_columns/volume.h
This fixes an ambiguous function call to `Gdiplus::DrawLine()` that VS 2019 16.7 was reporting.
However, compilation using 16.7 is still not possible as an internal compiler error occurs in `layout_config.cpp` relating to initializer_list usage.
=> Partially fix VS 2019 16.7 compilation errors

foo_ui_columns/item_details.cpp, foo_ui_columns/item_details.h, foo_ui_columns/item_details_font.cpp, foo_ui_columns/item_details_text.cpp
#321
This rewrites the sizing and word wrapping logic in the Items detail panel to fix a crash or possible heap corruption when Unicode code points above U+FFFF were encountered.
These changes include making Item details work in only UTF-16 internally; previously there was a mix of UTF-8 and UTF-16 which lead to complexity in counting code units.
Word wrapping behaviour will be slightly different to previous versions as a result of these changes.
=> Fix crash in Item details panel with certain emoji characters

Directory.Build.props, azure/pipeline.yml
This downgrades the VC tool set version on Azure Pipelines to the one from VS 2019 16.5 due to the 16.7 one currently producing an internal compiler error (and the 16.6 one not being available on Azure Pipelines).
=> Use older VC tool set version on Azure Pipelines

CHANGELOG.md, foo_ui_columns/foo_ui_columns.vcxproj
This updates to foobar2000 SDK 2020-07-28, and hence enables the use of SSE2 instructions.
=> Update to foobar2000 SDK 2020-07-28

CHANGELOG.md, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details.h, foo_ui_columns/stdafx.h
Fixes #331
This rewrites scroll bar-related code in Item details in an effort to improve behaviour when scroll bar information is updated, and fix a problem where it sometimes wasn't possible to scroll to the very bottom if both scroll bars were visible.
This also attempts to preserve the scroll position when changing settings.
=> Improve Item details scroll bar handling

CHANGELOG.md, foo_ui_columns/item_details_text.cpp
#337
This fixes a bug in Item details where font changes that were immediately followed by a colour code weren't correctly handled.
This also adjusts how line heights are calculated, so that if a font change is immediately followed by another one, the first font change is not ignored when calculating the height of the line.
=> Fix Item details incorrect handling of some font changes

CHANGELOG.md, foo_ui_columns/foo_ui_columns.vcxproj
Resolves #333
This was needed for Windows XP and old versions of Wine and can now be removed.
=> Remove use of /Zc:threadSafeInit- compiler option

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/artwork_helpers.h
Fixes #314
This adds support for back cover, disc and artist stub images to the artwork view.
These are configured on the main Display page in preferences.
The front cover stub image is used as a fallback if any of these three stub images fail to load (e.g. due to not being configured).
=> Add support for non-front cover stub images to artwork view

CHANGELOG.md, Directory.Build.props, azure/pipeline.yml, foo_ui_columns/layout_config.cpp
Fixes #327
There seems to be little sign that https://developercommunity.visualstudio.com/content/problem/1139127/internal-compiler-error-vs-1670.html will be resolved soon, so this applies the workaround mentioned in that link.
=> Work around VS 2019 16.7 compiler error

CHANGELOG.md
Fixes #306
This updates ui_helpers to pick up some changes to the list view scrolling speed when selecting items and during drag and drop.
See https://github.com/reupen/ui_helpers/pull/55 for more details.
=> Adjust list view scroll timer speed

CHANGELOG.md, foo_ui_columns/item_details_text.cpp
Fixes #330
This enables the expansion of tab characters in the Item properties and Item details panels.
Tab characters should be aligned as they would in a text editor or word processor.
In most other contexts, tab characters continue to activate the old pseudo-column functionality.
=> Expand tab characters in Item details and properties

CHANGELOG.md, foo_ui_columns/artwork.cpp
Resolves #346
This adds a 'Reload artwork' command to the artwork view panel.
This can be used to force a reload of artwork following e.g. configuration changes.
=> Add 'Reload artwork' context menu command to artwork view

CHANGELOG.md, foo_ui_columns/filter.cpp
This stops the Filter panel from focusing the first playlist item when using any of the send to playlist actions.
This improves compatibility with shuffle playback modes when 'Playback follows cursor' is enabled.
There is no change to the behaviour of the 'Add to active playlist' action.
=> Improve Filter panel compatibility with 'Playback follows cursor'

foo_ui_columns/config_appearance.cpp, foo_ui_columns/fonts_manager_data.cpp, foo_ui_columns/fonts_manager_data.h, foo_ui_columns/setup_dialog.cpp
This adds an implementation of the new `cui::fonts::manager_v2` service with custom DPI support.
This can be used to handle font sizes correctly when supporting per-monitor DPI.
=> Add cui::fonts::manager_v2 implementation

CHANGELOG.md, foo_ui_columns/buttons_config_param.cpp, foo_ui_columns/fcl.cpp, foo_ui_columns/item_details_config.cpp, foo_ui_columns/ng_playlist/ng_playlist_config.cpp, foo_ui_columns/rename_dialog.cpp, foo_ui_columns/setup_dialog.cpp, foo_ui_columns/vis_spectrum.cpp
This partially reverts #354 for the reasons mentioned in https://github.com/reupen/columns_ui/issues/353#issuecomment-752761004.
=> Partially revert 'Support per-monitor DPI in various dialogue boxes'

CHANGELOG.md
This updates the foobar2000 and pfc submodules to bring in changes from foobar2000 SDK 2021-01-29.
=> Update to foobar2000 SDK 2021-01-29

CHANGELOG.md, foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/splitter_panel.cpp, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/splitter_utils.cpp
This reworks the changes that were made in #320 so that the standard splitters no longer refresh a panel's configuration data when `splitter_window::get_panel()` is called.
This is to avoid panel configuration data being unnecessarily queried at strange moments (e.g. when the main window becomes inactive).
Instead, a refresh is done when a panel is being copied, which still fixes the original problem of stale configuration data being copied when a panel is copied during live editing.
=> Avoid querying panel configuration data unnecessarily

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/artwork_helpers.h
Resolves #365
This adds support for internet radio front covers to the artwork view panel when foobar2000 1.6.6 or newer is used.
Note that the implementation is somewhat complicated for the reasons described in the linked issue.
Some tidying up of artwork view panel-related code is also included.
=> Add support for dynamic front covers to artwork view panel

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h
This amends the logic in the Artwork view panel when the artwork type is not locked, so that if the panel switches to a different artwork type due to the selected artwork type not being available, the panel returns to the selected artwork type once it’s available again.
=> Return to selected artwork type after automatic switch in artwork view

CHANGELOG.md, foo_ui_columns/item_properties.cpp
Resolves #357
This makes Item properties append a '(not set)' to the values for a metadata field when:
- multiple tracks are selected
- only some of them have a value for a particular metadata field
- the number of values for that field is no more than the maximum number of values displayed (in which case an ellipsis is appended instead)
Additionally, a small change was made to show '(blank)' for metadata fields that are set to an empty string. (Fields containing only white space could also be more clearly shown, but that isn't tackled here.)
=> Show unset and blank values in Item properties more clearly

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/gdiplus.cpp, foo_ui_columns/gdiplus.h, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp
This fixes an oversight where stub images were still being loaded using GDI+ instead of the Windows Imaging Component in the Artwork view panel.
This was stopping formats such as WebP working for the stub image when appropriate system codecs are installed.
=> Use WIC to load stub image in Artwork view panel

CHANGELOG.md, foo_ui_columns/item_details_text.cpp
This fixes a regression caused by #323 where, when scrolling down in the Item details panel, colour codes would misbehave or, more rarely, a crash could occur.
=> Fix misbehaviour of colour codes when scrolling in Item details panel

foo_ui_columns/item_details.cpp, foo_ui_columns/item_details.h, foo_ui_columns/item_details_font.cpp, foo_ui_columns/item_details_text.cpp
This tidies up some bits of Item details code by:
- using consistent naming conventions
- renaming some types and variables
- deleting dead and commented-out code
=> Tidy up Item details code

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp
This makes group titles in the playlist view respect the 'Display ellipses in truncated text' playlist view option.
=> Respect show ellipses setting in playlist view group titles

CHANGELOG.md, foo_ui_columns/buttons_command_picker.cpp
Fixes #378
This fixes a problem where it wasn't possible to create a functioning button for the 'File operations/Rename to...' context menu command on current versions of foobar2000, and for other File operations context menu commands on older versions of foobar2000.
Note that any existing non-functioning buttons will need to have the relevant command re-selected in order for the button to function correctly.
=> Fix inability to create working buttons for some File operations commands 

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h
#380
This corrects some misbehaviour introduced in #368 when clicking on the artwork view panel to change artwork type.
It also makes a small tweak the the 'Lock artwork type' context menu command so that it always freezes the currently displayed artwork type when the setting is transitioned from disabled to enabled.
=> Fix misbehaviour when clicking on artwork view panel

CHANGELOG.md, foo_ui_columns/artwork.cpp
#380
This improves the Artwork view panel 'Reload artwork' context menu command by making it flush any cached image first, to ensure that a new image is always generated and a cached image is not reused.
It also fixes a bug that occurred when using the command, or when changing tracking mode, where dynamic internet artwork artwork was replaced with a stub image.
=> Improve behaviour of Reload artwork command

foo_ui_columns/drop_down_list_toolbar.h, foo_ui_columns/dsp_preset.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/order_dropdown.cpp, foo_ui_columns/output_device.cpp, foo_ui_columns/output_format.cpp, foo_ui_columns/replaygain_mode.cpp
I recently found myself having to constantly switch between formats while using two different output devices. While this attempt at a toolbar is quite crude (no option for toggling dithering for instance) it should be at least complimentary to the existing 'Output device' toolbar.
Fun fact: unlike output device changes, output format changes are not being tracked and kept in sync on the Preferences/Output page.
=> Add 'Output format' toolbar

CHANGELOG.md, foo_ui_columns/drop_down_list_toolbar.h
This makes drop-down list toolbars notify the host when size limits change.
This could be due to the configured font changing, or the items in the drop-down list changing.
Note that the toolbars with dynamic items only update their items when the drop-down list is clicked on (or otherwise expanded), as no callbacks are available to update them when the underlying list of items changes. Therefore, the minimum width also only updates on when the control is clicked on.
=> Make drop-down list toolbars notify host on size limit change

CHANGELOG.md, foo_ui_columns/drop_down_list_toolbar.h, foo_ui_columns/dsp_preset.cpp, foo_ui_columns/order_dropdown.cpp, foo_ui_columns/output_device.cpp, foo_ui_columns/output_format.cpp, foo_ui_columns/replaygain_mode.cpp
This makes the DSP preset toolbar display the text '(no DSP presets exist)' when no DSP presets have been created.
It also refactors how the drop-down list toolbar no-items text works slightly.
=> Add no-items text to DSP preset toolbar when no presets exist

README.md, foo_ui_columns/.clang-format, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/buttons_button_image.cpp, foo_ui_columns/commandline.cpp, foo_ui_columns/config_vars.cpp, foo_ui_columns/file_info_reader.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/main_window.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/rebar_band.h, foo_ui_columns/splitter_utils.cpp, foo_ui_columns/splitter_utils.h, foo_ui_columns/stdafx.h, foo_ui_columns/title_formatting.cpp, foo_ui_columns/version.h.template
This migrates from C++17 to C++20.
Clang compilation is broken as a result. This won't be fixed until the LLVM bundled with Visual Studio is updated to version 13 (containing https://reviews.llvm.org/D103155).
=> Migrate to C++20

.gitignore, CHANGELOG.md, README.md, azure/job-build.yml, azure/pipeline.yml, foo_ui_columns/buttons_custom_image.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/filter.h, foo_ui_columns/filter_inline_edit.cpp, foo_ui_columns/filter_items.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/playlist_switcher_drop_target.cpp, foo_ui_columns/playlist_tabs_drop_target.cpp, foo_ui_columns/status_pane.h, foo_ui_columns/stdafx.h, vcpkg.json
This updates submodules to bring in changes from foobar2000 SDK 2022-01-04.
Some bits of code were tidied up as part of this and `fmt` was added as a dependency (`std::format()` isn't used as it's not currently available in VS 2022 with the /std:c++20 compiler option).
Finally, vcpkg is now used in manifest mode to simplify handling of dependencies. Currently, only a single manifest in the root directory is used rather than having manifests for each project (I'm not sure how exactly the latter would behave, particularly if the manifests conflicted with each other).
=> Update to foobar2000 SDK 2022-01-04 and use vcpkg manifest mode

CHANGELOG.md, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/dark_mode_tabs.cpp, foo_ui_columns/dark_mode_tabs.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/splitter_tabs.cpp
This adds dark mode support to the playlist tabs and tab stack panels.
Unfortunately, the Windows tab control does not feature a native dark mode, and its owner-drawn mode is very limited, and so its own painting logic is overridden here.
The left/right buttons to scroll left and right when the tab control is in single row mode remain in a light mode.
=> Add dark modes for playlist tabs and tab stack

CHANGELOG.md, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/dark_mode_tabs.cpp, foo_ui_columns/filter_search_bar.cpp, foo_ui_columns/filter_search_bar.h, foo_ui_columns/splitter_panel_container.cpp
This:
- integrates the Filter search toolbar with Colours and fonts preferences and improves its dark mode
- tweaks the dark mode background colours of the playlist tabs and tab stack, and of panel captions
=> Improve Filter search dark mode and tweak some dark mode colours

CHANGELOG.md, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/rebar.cpp
This adds (subtle) dividers between rows and bands in the rebar in dark mode.
These are present in light mode and were previously missing in dark mode.
=> Add toolbar dividers in dark mode

CHANGELOG.md, README.md, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/dark_mode_trackbar.cpp, foo_ui_columns/dark_mode_trackbar.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/main_window.cpp, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/seekbar.cpp, foo_ui_columns/stdafx.h, foo_ui_columns/volume.h
This adds dark mode support to the trackbar controls in the seekbar and the various volume controls.
The Windows 11 SDK is now required (it can be installed using the Visual Studio 2022 installer).
=> Add dark mode to trackbars

CHANGELOG.md, foo_ui_columns/config_appearance.cpp, foo_ui_columns/config_appearance.h, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/foo_ui_columns.rc, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/resource.h, foo_ui_columns/tab_colours.cpp, foo_ui_columns/tab_dark_mode.cpp, foo_ui_columns/tab_dark_mode.h
This adds a toggle for dark mode to preferences.
Currently, the options are 'Light' or 'Dark'. A 'Use system setting' option will be added separately.
Changing the option requires restarting foobar2000. Live toggling will also be added separately.
This change also includes various OS version checks for dark mode.
=> Add dark mode toggle to preferences

foo_ui_columns/artwork.cpp, foo_ui_columns/buttons.cpp, foo_ui_columns/buttons_config_droptarget.cpp, foo_ui_columns/drop_down_list_toolbar.h, foo_ui_columns/filter.cpp, foo_ui_columns/filter_search_bar.cpp, foo_ui_columns/helpers.cpp, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details_text.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/layout.cpp, foo_ui_columns/menubar.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp, foo_ui_columns/rebar.cpp, foo_ui_columns/splitter.h, foo_ui_columns/splitter_panel.cpp, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/splitter_window.cpp, foo_ui_columns/splitter_window_wndproc.cpp, foo_ui_columns/status_bar.cpp, foo_ui_columns/stdafx.h, foo_ui_columns/tab_layout.cpp, foo_ui_columns/vis_spectrum.cpp
This adds a `#define NOMINMAX` to stop the Windows SDK headers defining `min()` and `max()` macros.
Various uses of the macros were updated to use C++ standard library equivalents.
=> Disable min() and max() macros

CHANGELOG.md, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/layout.cpp, foo_ui_columns/layout.h, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/splitter.cpp, foo_ui_columns/splitter_window_wndproc.cpp
The pseudo-transparent backgrounds added in #415 to the splitter panels and layout window reduced performance when resizing the main window for various reasons.
This removes the transparent backgrounds in favour of a simpler self-painted background.
=> Remove pseudo-transparent splitter panel background

CHANGELOG.md, foo_ui_columns/buttons_button_image.cpp
This fixes a regression added in #444 which caused a button in the buttons toolbar to have the wrong size if it was using a custom image that failed to load.
=> Fix incorrect button size when image fails to load

CHANGELOG.md, foo_ui_columns/playlist_tabs.cpp
#443
This fixes a problem where the playlist tabs was calculating its maximum width and height incorrectly in some cases due to integer overflow.
Mitigations for the same problem had already been put in place for the tab stack panel.
=> Fix incorrect size limit calculation in playlist tabs

.github/workflows/build.yml, CHANGELOG.md, foo_ui_columns/dark_mode_tabs.cpp, foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/playlist_tabs_wndproc.cpp, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/status_pane_msgproc.cpp, vc17/columns_ui-public.sln
This improves the playlist tabs and tab stack panels by:
- eliminating flickering when resizing panels by using double-buffered painting
- correcting the background colour of their containers in dark mode so that child panels with transparent panels render with a more appropriate background colour
=> Improve playlist tabs and tab stack rendering

foo_ui_columns/buttons.h, foo_ui_columns/config_appearance.cpp, foo_ui_columns/dark_mode.cpp, foo_ui_columns/rebar.h, foo_ui_columns/status_bar.h, foo_ui_columns/system_appearance_manager.cpp
This resolves a problem where menus were stuck in their previous mode after switching between light and dark modes. It also makes a few other minor tweaks.
=> Fix dynamic switching of menus between light and dark modes

CHANGELOG.md, README.md, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/helpers.cpp, foo_ui_columns/status_pane.cpp, foo_ui_columns/status_pane_msgproc.cpp, foo_ui_columns/vis_spectrum.cpp, foo_ui_columns/volume.h
This tidies up the definition of dark mode colours so that they are defined in a consistent way.
There's also a minor tweak to the spectrum analyser, and an update to the section in the README about downloading development versions.
=> Tidy up definitions of dark mode colours 

CHANGELOG.md, foo_ui_columns/buttons.cpp, foo_ui_columns/buttons_button.cpp, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h
This updates the buttons toolbar to:
- work around a problem where separators did not render correctly in dark mode
- correct the flat mode hover colours in dark mode
- correct the text flat mode hover text colour in non-ancient versions of Windows in light mode
=> Improve buttons toolbar dark mode

foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/rebar.cpp, foo_ui_columns/rebar.h
This:
- standardises on a single light background colour used in e.g. the toolbars
- adjusts the dark background colour on Windows 11 to be consistent with its File Explorer
- corrects the minimum Windows 10 build check for dark mode
=> Tweak dark mode background colours

foo_ui_columns/tab_colours.cpp
This corrects various colour patches in the Colours tab of the Colours and fonts page in preferences when both dark and themed modes are selected.
The update to ui_helpers also fixes a GDI object leak on that tab added in reupen/ui_helpers#63.
=> Correct dark mode themed colour patches in preferences

CHANGELOG.md, foo_ui_columns/filter_search_bar.cpp
This fixes a small problem where the Filter search would not update itself straight away when its colours were reconfigured.
=> Fix Filter search colours not updating instantly on change

foo_ui_columns/dark_mode.cpp, foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/playlist_tabs.h, foo_ui_columns/playlist_tabs_wndproc.cpp, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/splitter_tabs.h
Recent Windows 11 builds have dark mode support for up-down (spin) controls, so this makes use of that when it's available.
It also bumps the maximum Windows 11 build for using private dark mode APIs (i.e. for dark menus).
=> Add dark mode for tab control spin buttons on recent Windows 11

CHANGELOG.md
Previously, the seekbar and volume toolbar tooltips used a fixed offset of 21 pixels from the top of the pointer, which was incorrect for larger pointer sizes.
This updates ui_helpers to pick up a fix for this where the offset is now calculated dynamically based on the pointer size.
=> Use actual pointer size for seekbar and volume bar tooltip offset

CHANGELOG.md, foo_ui_columns/main_window.cpp
This fixes a small problem where, when resizing the main window vertically, toolbar sizing grips would render incorrectly (when the toolbars aren't locked).
=> Fix incorrect toolbar sizing grip rendering vertical main window resize

CHANGELOG.md, foo_ui_columns/splitter_panel.cpp, foo_ui_columns/splitter_panel_container.cpp
This updates the rendering logic for splitter panel containers to eliminate flicker of panel captions when resizing panels.
=> Eliminate panel caption flicker when resizing panels

CHANGELOG.md, foo_ui_columns/rebar.cpp, foo_ui_columns/rebar.h
This subclasses the rebar control to eliminate flickering of toolbar sizing grips when e.g. rearranging toolbars or switching between dark and light modes.
=> Eliminate flickering of toolbar sizing grips

CHANGELOG.md, foo_ui_columns/buttons.cpp, foo_ui_columns/colour_manager.cpp, foo_ui_columns/colour_manager_data.cpp, foo_ui_columns/colour_manager_data.h, foo_ui_columns/colour_utils.cpp, foo_ui_columns/colour_utils.h, foo_ui_columns/config.h, foo_ui_columns/config_appearance.cpp, foo_ui_columns/config_appearance.h, foo_ui_columns/dark_mode.cpp, foo_ui_columns/fcl_colours.cpp, foo_ui_columns/fcl_playlist_view.cpp, foo_ui_columns/filter_search_bar.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/helpers.cpp, foo_ui_columns/layout.h, foo_ui_columns/migrate.cpp, foo_ui_columns/rebar.cpp, foo_ui_columns/rebar.h, foo_ui_columns/setup_dialog.cpp, foo_ui_columns/setup_dialog.h, foo_ui_columns/status_bar.cpp, foo_ui_columns/system_appearance_manager.cpp, foo_ui_columns/tab_colours.cpp, foo_ui_columns/tab_colours.h, foo_ui_columns/vis_spectrum.cpp, foo_ui_columns/volume.h
This makes the colours configured on the Colours tab of Colours and fonts preferences specific to the active mode (light or dark).
This is so one person can switch between light and dark modes at their will, and have relevant colours configured for each.
On upgrade, any custom colours that are currently active are copied to the dark mode colour settings. This is in case someone already has dark colours configured (which would be otherwise difficult to copy across).
In the colour picker dialogue box shown when changing a custom colour, the custom colour available for selection at the bottom of the dialogue box was also corrected to be the default colour for the currently active mode.
Finally, the Colours tab is now refreshed if the colour mode is set to 'Use system setting' and the system …
=> Make light and dark mode colour settings independent

foo_ui_columns/config_appearance.cpp, foo_ui_columns/fcl.cpp, foo_ui_columns/fcl_colours.cpp, foo_ui_columns/fcl_playlist_view.cpp, foo_ui_columns/main_window.cpp, foo_ui_columns/tab_dark_mode.h
This adds all dark-mode related settings to configuration exports.
If a configuration without any dark mode settings is imported, light mode is automatically activated.
=> Add dark mode settings to FCL files

foo_ui_columns/main_window.cpp
This sets the default mode to 'Use system setting' on new installations. (Upgrades from older versions are unaffected.)
=> Set default colour mode to 'Use system setting' on new installations

CHANGELOG.md, foo_ui_columns/migrate.cpp, foo_ui_columns/vis_spectrum.cpp
This improves the logic for importing old per-instance spectrum analyser colours into the global unified configuration, so that the import is based on the first actual per-instance colours encountered, rather than the last values that were selected in the configuration dialogue box, as those could differ from the actual colours in some cases (e.g. after an FCL import).
=> Improve import of legacy spectrum analyser colours

CHANGELOG.md, foo_ui_columns/tab_layout.cpp
By default, the Win32 tree view control doesn't scale its indentation with the system DPI setting.
This corrects that on the Layout preferences page by telling the control to use the default indentation value.
=> Scale layout tree view indentation with system DPI

CHANGELOG.md, foo_ui_columns/dark_mode.cpp
This bumps the maximum allowed Windows 11 build for private dark mode APIs (i.e. dark menus).
The change log and submodules were also updated.
=> Update maximum allowed Windows 11 build for private dark mode APIs

CHANGELOG.md, foo_ui_columns/tab_dark_mode.cpp, foo_ui_columns/vis_spectrum.cpp
This fixes a problem with the spectrum analyser legacy colour configuration import logic that was causing colours to be set incorrectly for new installations.
It also changes references to Windows 10 20H1 to Windows 10 version 2004.
=> Fix incorrect spectrum analyser colours on new installations

CHANGELOG.md, foo_ui_columns/buttons.cpp, foo_ui_columns/buttons.h, foo_ui_columns/buttons_button_image.cpp
#546 
This updates the buttons toolbar to:
- fix a bug preventing ICO files from working as a custom hot button image
- fix a GDI object leak when using ICO files as custom images
- tidy up some of the button image code
=> Fix ICO file bugs in button toolbar

CHANGELOG.md, foo_ui_columns/buttons.cpp, foo_ui_columns/buttons.h, foo_ui_columns/buttons_button_image.cpp, foo_ui_columns/buttons_custom_image.cpp, foo_ui_columns/wic.cpp, foo_ui_columns/wic.h
Resolves #546
This resolves various odd behaviours when mixed size custom images are used in the buttons toolbar, by making the toolbar resize all images to the same size when mixed size images are detected.
=> Rework buttons toolbar image loading logic

CHANGELOG.md, foo_ui_columns/dark_mode.cpp
This stops active tabs in the Tab stack and Playlist tabs panels changing colour on hover when dark mode is active.
This is being changed as the previous behaviour was different from light mode, and generally unusual.
=> Stop active tabs changing colour on hover in dark mode

foo_ui_columns/foo_ui_columns.vcxproj
This turns on 'Use Debug Libraries' in debug configurations and removes various property overrides that are no longer needed as a result.
This also removes the inclusion of per-user property sheets as per https://docs.microsoft.com/en-gb/cpp/build/create-reusable-property-configurations.
=> Clean up project configuration

CHANGELOG.md, foo_ui_columns/buttons.h, foo_ui_columns/filter_search_bar.h
This resolves a problem where the padding of buttons in the buttons toolbar became incorrect when certain system settings were changed. In particular, this was observed after starting Adobe Photoshop.
The incorrect behaviour was due to buggy WM_SETTINGCHANGE handling in the Win32 toolbar control.
=> Fix buttons toolbar padding change on system setting change

CHANGELOG.md, foo_ui_columns/audio_track_toolbar.cpp, foo_ui_columns/drop_down_list_toolbar.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/pch.h
This adds a new toolbar called 'Audio track', which lets you select which audio track should be played if the playing file has multiple audio tracks (e.g. different languages).
This requires foobar2000 2.0 and is equivalent to 'Stream Selector' in the Default User Interface.
~Note: This requires the foobar2000 2.0 SDK which hasn't been merged into my repos yet.~
=> Add audio track toolbar

CHANGELOG.md, foo_ui_columns/user_interface_impl.cpp
This implements `user_interface_v3`, making various built-in foobar2000 windows use Columns UI mode, colour and font settings when Columns UI is active.
This requires foobar2000 2.0 or newer.
Some new 'Core' entries have been added to colours and fonts preferences for this.
For colours, only the text, background and selection background colours can be explicitly configured. The equivalent of the Default UI highlight colour currently isn’t configurable.
For fonts, the default, list items and console fonts can be individually configured.
Note: This requires the foobar2000 2.0 SDK which hasn't been merged into my repos yet.
=> Make various foobar2000 2.0 windows use Columns UI colours and fonts

CHANGELOG.md, foo_ui_columns/user_interface_impl.cpp
This resolves a problem following #574 where some foobar2000 windows used light mode colours in dark mode.
=> Fix core UI colours when dark mode is enabled

CHANGELOG.md, foo_ui_columns/tab_colours.cpp
This fixes various problems related to configuring a custom active item frame colour (which appears to have regressed a long time ago).
=> Fix inability to change active item frame colour in certain cases

CHANGELOG.md, foo_ui_columns/config.cpp, foo_ui_columns/config_appearance.cpp, foo_ui_columns/config_columns_v2.h, foo_ui_columns/config_filter.cpp, foo_ui_columns/config_host.cpp, foo_ui_columns/config_host.h, foo_ui_columns/config_layout.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/tab_display2.cpp, foo_ui_columns/tab_global.cpp, foo_ui_columns/tab_pview_artwork.cpp
This adds dark mode support to the root, Colours and fonts, Layout and Playlist switcher preference pages using foobar2000 core dark mode support.
Some other pages have been left out for now due to list view complexities. Various dialogue boxes also still need to be updated.
=> Add dark mode support to some preference pages

README.md
This makes the development build download instructions in README a bit clearer.
=> Improve development build download instructions in README

CHANGELOG.md, foo_ui_columns/user_interface_impl.cpp
Resolves #589
This fixes crashes when changing colours and fonts in foobar2000 1.x.
This was caused by #574.
=> Fix crashes when changing colours and fonts in foobar2000 1.x

CHANGELOG.md, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/metadb_helpers.h, foo_ui_columns/playlist_switcher_title_formatting.cpp, foo_ui_columns/status_bar.cpp, foo_ui_columns/status_pane.cpp
This optimises the calculation of the total length of multiple tracks in the status bar, status pane and playlist switcher, using the method that performed the best (at least for me).
=> Optimise calculation of total length of tracks in foobar2000 2.0

CHANGELOG.md, foo_ui_columns/config_filter.cpp, foo_ui_columns/core_dark_list_view.cpp, foo_ui_columns/core_dark_list_view.h, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters
This adds support for dark mode to Filter preferences in foobar2000 2.0.
=> Add dark mode support to Filter preferences

CHANGELOG.md, foo_ui_columns/core_dark_list_view.cpp, foo_ui_columns/list_view_panel.h
This makes the edit box used for inline editing in the various Columns UI list views (playlist view, playlist switcher, filters, item properties, filter preferences) have a dark appearance when dark mode is on.
It also fixes a glitch with the right border of the edit box at high DPIs, and prevents glitching during the initial render of the edit box.
=> Add dark mode to list view inline editing edit box

foo_ui_columns/dark_mode.cpp
As 22H2 is now generally available and dark mode menus don't work, the supported build version needs a bump.
https://blogs.windows.com/windowsexperience/2022/09/20/available-today-the-windows-11-2022-update/
edit: urgh, please excuse the typo in the commit message.
=> Update Windows 11 build number for dark mode support

CHANGELOG.md, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/splitter_tabs.h
This resolves a crash (due to an unhandled exception) in 64-bit builds that occurred when a Tab stack doesn't have an active tab (e.g. contains no tabs).
=> Fix 64-bit Tab stack crash when no tab is active

CHANGELOG.md, foo_ui_columns/setup_dialog.cpp
This fixes a regression in #595 that made selecting a layout preset in the Quick setup dialogue box have no effect.
=> Fix layout selection in Quick setup

CHANGELOG.md, foo_ui_columns/filter.cpp, foo_ui_columns/filter.h, foo_ui_columns/filter_inline_edit.cpp, foo_ui_columns/filter_items.cpp
This optimises the handling of media library additions and modifications. This is mainly by updating the list view in a more efficient manner. A smaller optimisation was also made related to how Filter nodes are stored in memory.
Optimising handling of media library additions and modifications is particularly important in foobar2000 2.0 where the media library initialises gradually.
=> Optimise Filter panel handling of media library changes

CHANGELOG.md, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/splitter_tabs.h
This eliminates or reduces the probability of the background of the tab control showing when switching tabs in the Tab stack panel.
(Other approaches could be taken if the problem remains, but I could no longer reproduce it with these changes.)
=> Reduce background show-through when switching tabs in Tab stack

CHANGELOG.md, foo_ui_columns/filter.cpp
This stops the Filter panel reporting initialisation times when it initialises before the media library does (on foobar2000 2.0).
This is because it resulted in incorrect times (such as zero seconds) being reported.
No time is now reported in such cases.
(Additionally, it no longer reports times when the media library is empty.)
=> Don't report Filter panel initialisation times if library not ready

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist_config.cpp
This fixes a crash when clicking Move down on the Grouping tab in playlist view preferences, when there wasn't a group selected.
This regressed in #595.
=> Fix crash when clicking Move down in playlist view preferences groups list

CHANGELOG.md, foo_ui_columns/dark_mode_tabs.cpp
Resolves #618
This resolves a problem in the Playlist tabs and Tab stack panels where tab names containing ampersands (& characters) didn't render correctly when dark mode is active.
=> Fix rendering of tabs containing ampersands in dark mode

CHANGELOG.md, foo_ui_columns/tab_display2.cpp
Resolves #621 
This resolves a problem where toggling the Alternative selection model option in playlist view preferences set the setting to the wrong value.
This regressed in #467.
=> Fix toggling of Alternative selection model playlist view setting

CHANGELOG.md
This updates `columns_ui-sdk` to pick up a fix to stop `container_uie_window_v3_t::destroy_window()` crashing if the panel window was already destroyed, or was never created.
=> Avoid crash in built-in panels when incorrectly destroyed

.gitmodules, CHANGELOG.md, foo_ui_columns/buttons.cpp, foo_ui_columns/buttons.h, foo_ui_columns/buttons_button_image.cpp, foo_ui_columns/buttons_custom_image.cpp, foo_ui_columns/pch.h, foo_ui_columns/wic.cpp, foo_ui_columns/wic.h
Resolves #553
This adds SVG support for custom images to the Buttons toolbar using the experimental [SVG services](https://github.com/reupen/svg-services) component. The SVG services component must be installed for this to work.
The SVG services repository has been added as a submodule to access the definition of its public API.
=> Add SVG support to buttons toolbar

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h
Resolves #602 
This changes how typing in the playlist view to jump to items works in foobar2000 2.0 to improve performance.
Previously, it formatted tracks and columns individually, including style scripts, where this information wasn't already cached.
Now, it formats tracks in large batches, and only formats the display script for the first column. This performs better in foobar2000 2.0. There is also no longer any long-term caching involved.
=> Optimise typing in playlist view to jump to items in foobar2000 2.0

CHANGELOG.md, foo_ui_columns/buttons.cpp
This removes some excess top and bottom padding in the buttons toolbar when both:
- ‘no edges’ mode is enabled; and
- no buttons are set to display with text
=> Remove top and bottom button padding in buttons toolbar no edges mode

CHANGELOG.md, foo_ui_columns/buttons.cpp, foo_ui_columns/buttons_button_image.cpp
This updates to the latest SVG services API and makes SVGs used in the buttons toolbar centred in the button when the SVG has a different aspect ratio to the button.
=> Centre SVGs in buttons in buttons toolbar

CHANGELOG.md, foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties.h, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_inline_edit.cpp
Resolves #304
This adds autocompletion to Item properties when editing metadata fields. The list of values is provided by the foobar2000 core.
The playlist view was also updated to use the latest `library_meta_autocomplete_v2` interface (which is said to include caching and asynchronicity).
=> Add autocompletion when editing metadata in Item properties

CHANGELOG.md, foo_ui_columns/dark_mode.cpp
This increases the maximum allowed build number for private Win32 dark mode APIs to build 22623 (a beta channel version).
=> Allow private Win32 dark mode APIs on Windows 11 build 22623

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist.cpp
Resolves #662 
This adds a Play command to the playlist view context menu when a single track is selected.
This should be there as it has been the usual convention on Windows (at least to Windows 7) to show the default command in the context menu (in bold).
=> Add Play command to playlist view context menu

CHANGELOG.md, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/dark_mode_spin.cpp, foo_ui_columns/dark_mode_spin.h, foo_ui_columns/dark_mode_tabs.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/splitter_tabs.h
Resolves #544 
This adds dark mode support to the Tab stack and Playlist tabs spin (up-down) control on Windows 10 and Windows 11 21H1.
This is, of course, a hack as the spin control has no native dark mode support.
There should be no change on Windows 11 22H2 where the spin control does have a native dark mode.
This also resolves some minor glitches that occurred when when using the scroll buttons (spin control) in the Tab stack and Playlist tabs panels with dark mode enabled.
=> Add dark mode support to tab control scroll buttons

CHANGELOG.md, foo_ui_columns/core_dark_list_view.cpp, foo_ui_columns/core_dark_list_view.h, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/dark_mode_active_ui.cpp, foo_ui_columns/dark_mode_active_ui.h, foo_ui_columns/dark_mode_dialog.cpp, foo_ui_columns/dark_mode_dialog.h, foo_ui_columns/event_token.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/main_window.cpp, foo_ui_columns/seekbar.h, foo_ui_columns/system_appearance_manager.h, foo_ui_columns/vis_spectrum.cpp, foo_ui_columns/volume.h
This adds dark mode support to the spectrum analyser options dialogue box.
Styling consistent with the rest of Columns UI is used (i.e. not core dark mode support), and foobar2000 1.5 and 1.6 are still supported.
=> Add dark mode support to spectrum analyser options

CHANGELOG.md, foo_ui_columns/foo_ui_columns.vcxproj
This no longer seems to be required.
=> Remove /Zc:preprocessor compiler option

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp
This fixes a crash when artwork is enabled in the playlist view and there is an error when creating an album art extractor object for a particular track.
This happened in particular with certain input components.
=> Fix playlist view artwork crash in certain error cases

CHANGELOG.md, foo_ui_columns/buttons.cpp, foo_ui_columns/buttons.h, foo_ui_columns/buttons_config_listview.cpp, foo_ui_columns/buttons_config_param.cpp, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/dark_mode_dialog.cpp, foo_ui_columns/dark_mode_dialog.h, foo_ui_columns/dark_mode_spin.cpp, foo_ui_columns/dark_mode_spin.h
This adds dark mode support to the Buttons options dialogue box.
This includes handling of spin controls adjacent to an edit control, and disabled checkboxes.
=> Add dark mode support to Buttons options

CHANGELOG.md, foo_ui_columns/dark_mode.cpp
Resolves #693 
This fixes a problem where the title bar of a maximised main window didn't correctly update when switching between light and dark mode.
This was fixed by switching to a different hack to force the title bar to redraw. A workaround is also no longer used on Windows 11, as it doesn't need one.
=> Fix update of maximised title bar when toggling dark mode

.github/workflows/build.yml, README.md, vc17/columns_ui-public.sln
This updates a few references to the default branch following a rename from `master` to `main`.
The Codiga badge was also removed from the README as the service is being shut down.
=> Update references to default branch

CHANGELOG.md, foo_ui_columns/drop_down_list_toolbar.h
This corrects the appearance of the scroll bar in all built-in drop-down list toolbars (including DSP manager and output device) when dark mode is enabled.
=> Fix drop-down toolbar scroll bar in dark mode

CHANGELOG.md, foo_ui_columns/item_properties_config.cpp
This fixes a regression caused by #683 on older versions of Windows, where the Item properties options tree view state image list was being leaked every time the dialogue was closed. This is linked to the use of the TVS_CHECKBOXES style.
This change destroys the image list as directed in the documentation. I was only able to reproduce the leak on older versions of Windows (e.g. Windows 7).
(The FCL import and export dialogues already had the logic to destroy the image list, so weren't affected by this problem.)
=> Fix GDI-object leak in Item properties dialogue box

CHANGELOG.md, foo_ui_columns/buttons.cpp
Some buttons toolbar console messages still referred to 'hot images'. These have been updated to refer to 'hover icons', in line with the rest of the UI.
=> Update buttons console messages about hover icons

CHANGELOG.md, foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/splitter_tabs.cpp
This updates the mouse wheel logic in the tab stack and playlist tabs panels so that it makes the tab control update its internal hover item state after scrolling. This is done by sending it a WM_MOUSEMOVE message. This resolves some rendering glitches in both light and dark modes.
(There is some scope to refactor things so that more logic is shared between the two panels, though that is out of scope here.)
=> Make tab control update hover item when using the mouse wheel

.github/workflows/build.yml, README.md
This fixes the Clang build following the change made to vcpkg in https://github.com/microsoft/vcpkg/pull/31239.
=> Fix Clang build

CHANGELOG.md, foo_ui_columns/audio_track_toolbar.cpp, foo_ui_columns/core_drop_down_list_toolbar.h, foo_ui_columns/drop_down_list_toolbar.h, foo_ui_columns/dsp_preset.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/order_dropdown.cpp, foo_ui_columns/output_format.cpp, foo_ui_columns/playlist_selector.cpp
Resolves #691
This adds a drop-down toolbar for switching between playlists, based on the core `fb2k::toolbarDropDown` interface.
The toolbar name 'Playlist' would be more consistent with other built-in toolbars, but I've made an exception to the usual naming scheme here and added the word 'selector', as 'playlist' on its own could refer to the contents of the playlist.
=> Add playlist selector toolbar

CHANGELOG.md, foo_ui_columns/config_vars.cpp, foo_ui_columns/config_vars.h, foo_ui_columns/main_window.cpp
Resolves #706
This makes the saving and restoring of the main window position between foobar2000 sessions DPI aware. If the system DPI changes between foobar2000 sessions, the position will be scaled accordingly.
(There may be some scope to further improve things by digging into the monitor configuration, but there is a lot of potential complexity there so it's not done here.)
=> Make saved main window position DPI aware

CHANGELOG.md, foo_ui_columns/item_details.cpp
Resolves #705 
This stops Item details from reading full file info on foobar2000 2.0 and up, as  it isn’t needed (foobar2000 2.0 always loads large fields like lyrics).
=> Don't read full file info in Item details on foobar2000 2.0 and newer

CHANGELOG.md, foo_ui_columns/buttons_config_param.cpp, foo_ui_columns/config_columns_v2.cpp, foo_ui_columns/config_filter.cpp, foo_ui_columns/item_details_config.cpp, foo_ui_columns/ng_playlist/ng_playlist_config.cpp, foo_ui_columns/prefs_utils.h, foo_ui_columns/rename_dialog.cpp, foo_ui_columns/tab_display2.cpp, foo_ui_columns/tab_global.cpp, foo_ui_columns/tab_layout.cpp, foo_ui_columns/tab_layout_misc.cpp, foo_ui_columns/tab_main.cpp, foo_ui_columns/tab_notification_area.cpp, foo_ui_columns/tab_playlist_dd.cpp, foo_ui_columns/tab_playlist_swticher.cpp, foo_ui_columns/tab_pview_artwork.cpp, foo_ui_columns/tab_status_bar.cpp, foo_ui_columns/tab_status_pane.cpp
Resolves #572 
This adds standardised handling of Ctrl+Backspace and Ctrl+A in all edit controls that are created by Columns UI.
=> Improve consistency of Ctrl+Backspace and Ctrl+A in edit controls

CHANGELOG.md, foo_ui_columns/dark_mode_tabs.cpp
Resolves #709
This fixes a minor rendering glitch below the playlist tabs and tab stack panels when dark mode is enabled. Previously, a tab would render in this small space, but did not re-render when scrolling. Now, tabs are not rendered in that small space and only the background colour shows through,
=> Fix dark mode rendering glitch below tab spin buttons

CHANGELOG.md, foo_ui_columns/playlist_switcher_v2.h
Resolves #710
This makes the playlist switcher panel search by the real playlist name when typing in the panel if title formatting is used. Previously, it searched by the formatted title that was displayed.
=> Always search by actual playlist name when typing in playlist switcher

CHANGELOG.md, foo_ui_columns/config_columns_v2.cpp, foo_ui_columns/tab_pview_artwork.cpp
Resolves #739
This resolves a regression following #735 where there was a stack overflow in on the playlist view columns preferences page, due to edit controls being subclassed multiple times.
=> Fix crash in playlist view columns preferences

CHANGELOG.md, foo_ui_columns/layout.cpp
Resolves #736 
This resolves misbehaviours when right-clicking on the non-client area (such as on scroll bars) of panels when live editing is active.
=> Fix right-clicking on panel non-client area during live editing

CHANGELOG.md, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_callbacks.cpp, foo_ui_columns/ng_playlist/ng_playlist_config.cpp, foo_ui_columns/ng_playlist/ng_playlist_prefs_groups.cpp
Resolves #715
This adds saving and restoring of playlist view vertical scroll positions between foobar2000 sessions for all playlists. Previously, the focused item was scrolled to after closing and reopening foobar2000.
=> Save playlist view scroll positions between sessions

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_callbacks.cpp, foo_ui_columns/ng_playlist/ng_playlist_config.cpp
This:
- refactors the playlist view playlist callback code to be a little bit tidier
- fixes regression from #742 causing crashes when no playlist is active (e.g. happens when using the Edit/Undo command)
=> Fix crash when no playlist is active

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_callbacks.cpp, foo_ui_columns/playlist_switcher_drop_target.cpp, foo_ui_columns/playlist_tabs_drop_target.cpp
Resolves #714 
This makes some behaviour changes to improve the behaviour when tracks are added to a non-active playlist using drag and drop:
- when tracks are dropped on an existing playlist in the playlist switcher and playlist tabs panels, the first newly added item is focused
- when the focused item in a non-active playlist changes, the playlist view scrolls to that item the next time the playlist is activated
=> Improve behaviour when dropping tracks on non-active playlist

CHANGELOG.md, foo_ui_columns/seekbar.cpp, foo_ui_columns/volume.h
Resolves #758
This makes the seekbar and volume bar tooltips dark when dark mode is active.
=> Add dark mode to seekbar and volume bar tooltips

CHANGELOG.md, foo_ui_columns/buttons_stock.cpp
This fixes a problem where the default stop after current icon sometimes did not show. This was due to there being two different`uie::button` implementations for the command.
=> Fix stop after current icon intermittently not loading

CHANGELOG.md, foo_ui_columns/main_window.cpp, foo_ui_columns/main_window.h, foo_ui_columns/mw_wnd_proc.cpp
Resolves #713 
This adjusts the updating of taskbar buttons to use `PostMessage()` rather than a `main_thread_callback`. Why this makes a difference is unclear: the lag is neither when `fb2k::inMainThread()` is called nor when the callback function is called. The reason may be related to `ITaskbarList3::ThumbBarUpdateButtons()` calling `SendMessageTimeout()` (without `SMTO_BLOCK`) which was previously noted as being the cause of unexpected problems.
(Doing the taskbar button updates off the main thread is an option, but I don't believe that should be needed with this change.)
=> Work around lag when starting playback of a track

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp
This updates grouping in the playlist view:
- each group level is no longer indented
- padding either side of artwork was reduced
- artwork reflection is now disabled by default
=> Adjust playlist view grouping layout

CHANGELOG.md, foo_ui_columns/dark_mode.cpp
This increases the maximum allowed build number for private Win32 dark mode APIs to build 226311 (a beta channel version).
=> Enable dark menus on Windows 11 build 22631

CHANGELOG.md, foo_ui_columns/dark_mode.cpp, foo_ui_columns/dark_mode.h, foo_ui_columns/main_window.cpp, foo_ui_columns/tab_colours.cpp
- Allow Windows builds greater than 22631 to access "private" APIs. (Tested on Windows 11 Insiders Canary build 25926)
- Update `PreferredAppMode` enum
- Call `AllowDarkModeForWindow` (`@133`) from `dark::set_titlebar_mode`. This fixes the menubar / context menus to use dark mode.
Tested both the x86 build (with foobar2000 v1.6.16) and the x64 build (with foobar2000 v2.1 preview 2023-08-01).
=> Enable dark menus on Windows 11 builds greater than 22631

foo_ui_columns/main_window.cpp, foo_ui_columns/status_bar.cpp, foo_ui_columns/volume.h
This resolves a problem where a console message stating 'UnregisterClass failed: Class does not exist' was logged at exit.
=> Fix UnregisterClass failed console message at exit

CHANGELOG.md, foo_ui_columns/version.cpp, foo_ui_columns/version.h.template
Resolves #778 
This simplifies the copyright notice, including using the year of compilation as the copyright date.
=> Update copyright notice

CHANGELOG.md, foo_ui_columns/fcl_titles.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/tab_global.cpp
This resolves a problem where the empty area at the bottom of the playlist view (when there are only a few items) was not immediately redrawn when the background colour was reconfigured.
=> Redraw entire playlist view on background colour change

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist_config.cpp
This fixes a problem causing console warnings when adding a playlist view to the layout. The problem was due to the panel not handling an empty configuration correctly.
=> Fix console warning when adding playlist view to layout

CHANGELOG.md, foo_ui_columns/get_msg_hook.cpp, foo_ui_columns/helpers.cpp, foo_ui_columns/helpers.h, foo_ui_columns/playlist_tabs.h, foo_ui_columns/playlist_tabs_wndproc.cpp, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/splitter_tabs.h
Resolves #146
This adds support for using Ctrl-Tab and Shift-Ctrl-Tab to switch tabs in the Playlist tabs and Tab stack panels.
This wasn't straightforward to implement; both component have little control over the contents of children, and  can also contain nested tabs. Nonetheless, this solution should handle most scenarios well.
Additionally, the existing code to update the keyboard focus when switching tabs in the Tab stack wasn't working correctly. This has been fixed as part of this, and the focus is now set to the first focusable element in the new tab (unless the tabs themselves were previously focused, or the new tab doesn't have any focusable children).
=> Add support for Ctrl-Tab to Playlist tabs and Tab stack

CHANGELOG.md, foo_ui_columns/mw_wnd_proc.cpp
This works around a Windows bug that can cause visual glitches after running a full-screen game at a reduced resolution under a multiple-monitor set-up.
The problem is described in more detail at https://hydrogenaud.io/index.php/topic,125030.msg1038153.
=> Work around visual glitches after running full-screen games

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp, foo_ui_columns/rebar.cpp, foo_ui_columns/splitter_panel_container.cpp
Resolves #837
This improves support for high contrast mode on recent versions of Windows. It:
- fixes colour-related problems in list views when a high contrast theme is enabled
- fixes various visual glitches immediately after switching to or from a high contrast theme
=> Improve support for high contrast mode

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h
Relates to #717
This adds a context menu command to the Artwork view panel that opens the currently displayed image in the foobar2000 picture viewer.
=> Add open in pop-up viewer context-menu command to Artwork view

CHANGELOG.md, foo_ui_columns/dark_mode_tabs.cpp
This fixes various rendering glitches in Playlist tabs and Tab stack when dark mode is active. In particular, problems with tab borders are low DPIs were fixed.
=> Fix various rendering glitches with dark mode tabs

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/config_artwork.cpp, foo_ui_columns/foo_ui_columns.rc, foo_ui_columns/main_window.cpp, foo_ui_columns/migrate.cpp, foo_ui_columns/migrate.h, foo_ui_columns/resource.h
Resolves #717
This makes action performed when clicking on the Artwork view panel configurable in preferences.
There are two options:
- open in foobar2000 picture viewer (available on foobar2000 1.6.2 and newer only)
- show next available artwork type (the previous standard behaviour)
On new installations of Columns UI, 'Open in foobar2000 picture viewer' is now the default (if using foobar2000 1.6.2 or newer).
=> Add option to open picture viewer on Artwork view click

CHANGELOG.md, foo_ui_columns/artwork.cpp
This fixes a small bug in the Artwork view panel where, when a stream with dynamic artwork is playing and the playing track is selected, changing the 'Displayed track' from one that doesn't include the playing item to one that does would not immediately show the streaming artwork as expected.
=> Correctly show streaming artwork after changing 'Displayed track'

CHANGELOG.md, foo_ui_columns/filter_search_bar.cpp
Resolves #720 
This makes the behaviour of clearing the Filter search toolbar when there are no Filter panels in the layout consistent with the behaviour when there are Filter panels in the layout.
Both cases now return all items in the media library.
=> Always return all items when clearing the Filter search toolbar

CHANGELOG.md, foo_ui_columns/file_info_utils.cpp, foo_ui_columns/file_info_utils.h, foo_ui_columns/filter.cpp, foo_ui_columns/filter.h, foo_ui_columns/filter_inline_edit.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties.h, foo_ui_columns/list_view_panel.h, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/ng_playlist/ng_playlist_inline_edit.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp, foo_ui_columns/ng_playlist/ng_playlist_style.cpp, foo_ui_columns/playlist_switcher.cpp, foo_ui_columns/playlist_switcher.h
This makes the way Item properties and Filter panel write metadata changes when using inline editing more consistent with the playlist view.
In particular, more logic is pushed to the `file_info_filter` class. This should also improve safety, as it causes changes to be applied to freshly read metadata, rather than the cached copy.
Some code was cleaned up at the same time.
=> Improve metadata saving logic in Item properties and Filter panel

CHANGELOG.md
Resolves #865 
This updates ui_helpers to fix a bug causing the playlist view scroll position to be shown incorrectly if the act of switching playlists caused the vertical scroll bar to be shown.
=> Fix incorrect playlist view scroll position after playlist switch

CHANGELOG.md, foo_ui_columns/file_info_utils.cpp, foo_ui_columns/file_info_utils.h, foo_ui_columns/item_properties.cpp, foo_ui_columns/ng_playlist/ng_playlist_inline_edit.cpp
Resolves #414
This updates inline editing in the playlist view and in Item properties so that, when multiple tracks are being edited, if the current values of the field differ between the tracks those current values are included in the edit box after the text `«mixed values»`.
=> Include current values in inline editing edit box when values are inconsistent

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist_clipboard.cpp, foo_ui_columns/playlist_switcher_drop_target.cpp
Resolves #864 
This resolves a bug where it wasn’t possible to paste files that had been copied in File Explorer in the playlist view using the context menu.
=> Fix ability to paste files copied in File Explorer in the playlist view

CHANGELOG.md, foo_ui_columns/buttons.cpp
Resolves #887 
This resolves a problem where an item group of ‘None’ caused a context menu command not to be executed.
(Note that this executes the context menu command without any items which is normally not useful.)
=> Fix behaviour of the 'None' item group in Buttons toolbar

CHANGELOG.md, foo_ui_columns/tab_layout.cpp
#880 
This adds a message box to confirm the deletion of a layout preset, when clicking the Delete button on the Layout preferences tab.
This message box can be bypassed (e.g. when deleting a lot of presets) by holding down the Shift button while clicking the button.
=> Add confirmation before deleting layout presets

CHANGELOG.md, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/status_bar.cpp
#15
This makes the status bar use DirectWrite to render text rather than a mix of Uniscribe and GDI.
This brings improved text rendering, including sub-pixel positioning and improved handling of colour changes.
This includes colour font support on Windows 8.1 and newer.
=> Use DirectWrite to render text in the status bar

CHANGELOG.md, foo_ui_columns/config_columns_v2.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist_prefs_groups.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp, foo_ui_columns/playlist_switcher_v2.cpp, foo_ui_columns/setup_dialog.cpp, foo_ui_columns/status_bar.cpp
#15
This makes list views (including the playlist view, playlist switcher, Filter panel and Item properties) render text using DirectWrite rather than Uniscribe.
Tooltips and inline editing edit controls remain unchanged.
=> Migrate list views to DirectWrite

CHANGELOG.md, foo_ui_columns/dark_mode_dialog.cpp, foo_ui_columns/item_details_config.cpp
Resolves #896
When Items details options was opened in modal mode (for example from Layout preferences), it always opened in light mode.
This corrects that so it opens in dark mode when dark mode is active.
=> Make Items details options support dark mode when in modal mode

CHANGELOG.md, foo_ui_columns/config_columns_v2.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/font_manager.cpp, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/font_manager_data.h, foo_ui_columns/font_manager_v3.cpp, foo_ui_columns/font_manager_v3.h, foo_ui_columns/font_utils.cpp, foo_ui_columns/font_utils.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/item_properties.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist_prefs_groups.cpp, foo_ui_columns/playlist_switcher_v2.cpp, foo_ui_columns/setup_dialog.cpp, foo_ui_columns/status_bar.cpp, foo_ui_columns/tab_fonts.cpp, foo_ui_columns/tab_fonts.h
This makes changes to how fonts selected in the Colours and fonts preferences page are saved so that DirectWrite-compatible properties are retained and the selected DirectWrite font can be used by panels.
A preliminary version of a `cui::fonts::manager_v3` interface was added in order to allow panels to access the extended font configuration.
Note that none of this yet fully supports the [typographic font family model](https://learn.microsoft.com/en-us/windows/win32/directwrite/font-selection#typographic-font-family-model) and variable font axes.
=> Save DirectWrite font family, weight, stretch, style and DIP size

.flake8, .pre-commit-config.yaml, pyproject.toml
This replaces the Flake8, Black and isort pre-commit hooks used for Python with Ruff.
=> Replace Flake8, Black and isort pre-commit hooks with Ruff

CHANGELOG.md, foo_ui_columns/font_utils.cpp, foo_ui_columns/tab_fonts.cpp
This resolves a problems where the font size wasn't set correctly when it was typed (rather than when using the arrow buttons) in preferences.
It also fixes a problem where the correct sign wasn't used when importing font sizes from fairly old versions of Columns UI.
=> Fix incorrect behaviour when typing a font size

CHANGELOG.md, foo_ui_columns/status_bar.cpp
This fixes a crash in the status bar when:
- it's configured with a very small font size (~1 pt)
- the playlist lock section is enabled and a locked playlist is active
- SVG services is installed
=> Fix crash in status bar with very small font size

CHANGELOG.md, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/font_manager_data.h
Unfortunately, due to a bug in the font configuration data reader, downgrading to the release version of Columns UI was causing incorrect custom font sizes to be read.
This reworks how the font configuration data is written so that things remain backwards compatible with the release version of Columns UI.
Note that the extended DirectWrite-specific font configuration data written by recent development versions of Columns UI won't be read by this version due to the change in how the configuration data is written (and therefore font configuration will be reimported from the old GDI-based configuration structures).
=> Store extended font configuration in backwards-compatible way

CHANGELOG.md, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details.h, foo_ui_columns/item_details_config.cpp, foo_ui_columns/item_details_font.cpp, foo_ui_columns/item_details_text.cpp, foo_ui_columns/item_details_text.h, foo_ui_columns/tab_fonts.cpp
Resolves #929
This makes the Item details panel render text using DirectWrite rather than Uniscribe.
All the custom text layout and word wrapping code has been removed as DirectWrite handles this natively.
Note that, currently, it's only possible to specify GDI-compatible fonts using the `$set_font()` title formatting function. (`$set_font()` does now accept non-integer font sizes, however.)
=> Migrate Item details to DirectWrite

CHANGELOG.md, foo_ui_columns/font_manager_v3.cpp, foo_ui_columns/font_manager_v3.h, foo_ui_columns/font_utils.cpp, foo_ui_columns/font_utils.h, foo_ui_columns/menu_items.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/tab_fonts.cpp
Resolves #928
This updates the ‘View/Playlist view/Decrease font size’ and ‘View/Playlist view/Increase font size’ menu commands to simply increase or decrease the font size by 1pt instead of trying to enumerate font sizes using GDI (which is no longer relevant, now DirectWrite is being used).
A new method was added to the preliminary `cui::fonts::manager_v3` interface to accommodate this functionality through the API.
=> Update playlist view font size menu command logic

CHANGELOG.md, foo_ui_columns/foo_ui_columns.rc
This resolves a problem where the ‘Alignment’ label in the Columns tab of the Playlist view preferences page was clipped for some display scale setting values.
=> Fix clipped Alignment label in preferences

CHANGELOG.md, foo_ui_columns/config_appearance.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/font_manager_data.h, foo_ui_columns/font_manager_v3.cpp, foo_ui_columns/font_manager_v3.h, foo_ui_columns/font_utils.cpp, foo_ui_columns/font_utils.h, foo_ui_columns/foo_ui_columns.rc, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/item_details_text.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/list_view_panel.h, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp, foo_ui_columns/playlist_switcher_v2.cpp, foo_ui_columns/resource.h, foo_ui_columns/status_bar.cpp, foo_ui_columns/status_pane.cpp, foo_ui_columns/status_pane_msgproc.cpp, foo_ui_columns/tab_text_rendering.cpp, foo_ui_columns/tab_text_rendering.h
Resolves #932
This allows the configuration of the DirectWrite rendering mode, and whether to force the use of greyscale anti-aliasing.
These options apply to built-in parts of the main UI that use DirectWrite for text rendering, and will also be exposed in the updated font API.
Hopefully these options should be enough to keep anyone that doesn't like the default appearance of DirectWrite text happy.
=> Allow configuration of some DirectWrite rendering options

CHANGELOG.md, foo_ui_columns/tab_text_rendering.cpp
This fixes a problem where when the 'Text rendering' preferences tab would initially show the inverse value of the 'Force greyscale anti-aliasing' option.
=> Fix restoration of 'Force greyscale anti-aliasing' option in preferences

CHANGELOG.md, foo_ui_columns/item_details.cpp, foo_ui_columns/main_window.h, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp, foo_ui_columns/status_bar.cpp, foo_ui_columns/status_pane_msgproc.cpp, foo_ui_columns/tab_fonts.cpp
Resolves #931 
This improves DirectWrite multi-monitor support by using monitor-specific rendering parameters.
As a result, the main window now invalidates itself and all children when moving between monitors. (In theory, other top-level windows containing panels should too, but that is difficult to enforce...)
=> Improve DirectWrite multi-monitor support

CHANGELOG.md, docs/source/item-details/title-formatting.md, foo_ui_columns/file_info_utils.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details_font.cpp, foo_ui_columns/item_details_text.cpp, foo_ui_columns/item_details_text.h, foo_ui_columns/pch.h, foo_ui_columns/string.cpp, foo_ui_columns/string.h, foo_ui_columns/tab_fonts.cpp, foo_ui_columns/title_formatting.cpp, foo_ui_columns/title_formatting.h
#950
This adds a new title formatting function, `$set_format()`, to Item details.
This is a replacement for the older `$set_font()` function.
The new function takes a single argument, which is a CSS-like string. For example:
```
$set_format(
font-family: Segoe UI Variable;
font-size: 20;
font-weight: 300;
font-stretch: 5;
font-style: italic;
text-decoration: underline;
)
```
Properties can be omitted (in which case they will retain their current value).
A special value of `initial` can be used to reset any particular property to its default value.
The `$reset_format()` function can be used to reset all properties to their defaults in one go.
=> Add new $set_format() title formatting function to Item details

.github/workflows/auto-merge.yml, vc17/columns_ui-public.sln
This adds, as a trial, a workflow to automatically merge Dependabot and pre-commit pull requests.
This is based on the example on https://docs.github.com/en/code-security/dependabot/working-with-dependabot/automating-dependabot-with-github-actions.
Pull requests with more than 1 commit are ignored, and for pre-commit PRs there is an additional check that only `.pre-commit-config.yaml` has been modified.
=> Add workflow to auto-merge dependency update pull requests

CHANGELOG.md, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details_format_parser.cpp, foo_ui_columns/item_details_format_parser.h, foo_ui_columns/item_details_text.cpp, foo_ui_columns/item_details_text.h, foo_ui_columns/lexy_user_config.hpp, foo_ui_columns/pch.h, foo_ui_columns/string.cpp, foo_ui_columns/string.h, vcpkg-configuration.json, vcpkg-ports/foonathan-lexy/portfile.cmake, vcpkg-ports/foonathan-lexy/vcpkg.json, vcpkg.json
#950 
This replaces with previous primitive Item details format string parser with a much better one using [lexy](https://github.com/foonathan/lexy).
For now, the library has been forked to fix Win32 (x86) builds in Visual Studio.
=> Add better Item details format string parser

CHANGELOG.md, docs/source/item-details/title-formatting.md, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details_config.cpp, foo_ui_columns/item_details_format_parser.cpp, foo_ui_columns/item_details_format_parser.h, foo_ui_columns/pch.h
Resolves #950
This adds support for percentage `font-stretch` values when using `$set_format()` in Item details.
Note that a `%` character needs to be escaped in title formatting, therefore percentages for `font-stretch` need to be written as e.g. `100%%` or `100pc`.
The percentage values are most useful on recent versions of Windows where variable font axes are supported.
=> Add support for percentage font-stretch values in Item details

.github/workflows/auto-merge.yml
This switches to using a reusable workflow for enabling auto-merge on Dependabot and pre-commit pull requests.
=> Use reusable workflow for auto-merging

CHANGELOG.md, foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/rebar.cpp, foo_ui_columns/splitter_tabs.cpp
This subclasses the Tab stack and Playlist tabs spin control to eliminate flickering when resizing the panel.
=> Eliminate Playlist tabs and Tab stack spin control flickering

CHANGELOG.md, foo_ui_columns/item_details_text.cpp
Resolves #1036
This resolves a problem where some colour and format codes were ignored in Item details. This occurred when a format code appeared after a colour code, and vice versa, immediately followed by the end of the string.
=> Fix problem with some Item details colour and format codes being ignored

CHANGELOG.md, foo_ui_columns/fcl_fonts.cpp, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/font_manager_data.h
Resolves #962
This adds reading and writing of new DirectWrite-related font properties and text rendering options to FCL files.
=> Add new font properties and text rendering options to FCL files

CHANGELOG.md, foo_ui_columns/dark_mode.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/system_tray.cpp, foo_ui_columns/win32.cpp, foo_ui_columns/win32.h
Resolves #1010
Windows 11 handles ampersands in system tray icon tooltips differently from earlier versions of Windows. Microsoft has shown no interest in fixing the problem (or even accepting that the problem exists), therefore this adds a nasty `if <is windows 11>` to work around the problem.
=> Work around different handling of ampersands in Windows 11 system tray

CHANGELOG.md, foo_ui_columns/commandline.cpp, foo_ui_columns/config_filter.cpp, foo_ui_columns/dark_mode_dialog.cpp, foo_ui_columns/dark_mode_dialog.h, foo_ui_columns/font_picker.cpp, foo_ui_columns/helpers.cpp
This adds dark mode support to info boxes. Info boxes are used for Filter field help, and some CLI command errors.
=> Add dark mode support to info boxes

CHANGELOG.md, foo_ui_columns/buttons_config_param.cpp, foo_ui_columns/commandline.cpp, foo_ui_columns/config_filter.cpp, foo_ui_columns/dark_mode_dialog.cpp, foo_ui_columns/dark_mode_dialog.h, foo_ui_columns/font_picker.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/helpers.cpp, foo_ui_columns/layout.cpp, foo_ui_columns/main_window.cpp, foo_ui_columns/playlist_switcher_v2.h, foo_ui_columns/splitter_utils.cpp, foo_ui_columns/splitter_utils.h, foo_ui_columns/tab_layout.cpp, foo_ui_columns/tab_main.cpp
This replaces all uses of `MessageBox()` with modal info boxes, which brings dark mode support and more consistent appearance with the rest of Columns UI.
=> Replace message boxes with modal info boxes

CHANGELOG.md, foo_ui_columns/buttons.h, foo_ui_columns/buttons_command_picker.cpp, foo_ui_columns/buttons_config_param.cpp, foo_ui_columns/dark_mode_dialog.cpp, foo_ui_columns/fcl.cpp, foo_ui_columns/font_picker.cpp, foo_ui_columns/item_details_config.cpp, foo_ui_columns/rename_dialog.cpp, foo_ui_columns/setup_dialog.cpp, foo_ui_columns/vis_spectrum.cpp
This switches to using new fbh helpers for modeless and modal dialogs that handle `ModalDialogPrologue()`, `modal_dialog_scope` and `modeless_dialog_manager` automatically.
This in turn makes usage of `ModalDialogPrologue()` and `modal_dialog_scope` for modal dialogs more consistent than it was previously.
=> Use modal_dialog_scope and modeless_dialog_manager consistently

CHANGELOG.md, foo_ui_columns/tab_layout.cpp
Resolves #880
This prevents the deletion of the last layout preset when using the Delete button on the Layout preferences page.
(Previously, the preset was deleted and replaced with the a preset containing the default layout.)
=> Prevent deletion of last layout preset

CHANGELOG.md, foo_ui_columns/buttons.h, foo_ui_columns/buttons_config_listview.cpp, foo_ui_columns/config_filter.cpp, foo_ui_columns/filter.h, foo_ui_columns/filter_inline_edit.cpp, foo_ui_columns/font_manager_v3.cpp, foo_ui_columns/font_picker.cpp, foo_ui_columns/font_picker.h, foo_ui_columns/font_utils.cpp, foo_ui_columns/item_details_text.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties.h, foo_ui_columns/item_properties_config_list_view.cpp, foo_ui_columns/main_window.h, foo_ui_columns/mw_drop_target.h, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_clipboard.cpp, foo_ui_columns/ng_playlist/ng_playlist_inline_edit.cpp, foo_ui_columns/playlist_manager_utils.cpp, foo_ui_columns/playlist_switcher_inline_edit.cpp, foo_ui_columns/playlist_switcher_title_formatting.cpp, foo_ui_columns/playlist_switcher_v2.cpp, foo_ui_columns/playlist_switcher_v2.h, foo_ui_columns/playlist_tabs.h, foo_ui_columns/playlist_tabs_wndproc.cpp, foo_ui_columns/wic.cpp, foo_ui_columns/wic.h
This updates mmh, ui_helpers and fbh, and replaces some uses of some legacy helpers that have been removed from those libraries.
=> Replace uses of legacy helpers

CHANGELOG.md, foo_ui_columns/fcl_fonts.cpp, foo_ui_columns/filter.cpp, foo_ui_columns/font_manager.cpp, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/font_manager_data.h, foo_ui_columns/font_manager_v3.cpp, foo_ui_columns/item_details_config.cpp, foo_ui_columns/item_details_text.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/playlist_switcher_v2.cpp, foo_ui_columns/status_bar.cpp, foo_ui_columns/status_pane.cpp, foo_ui_columns/system_appearance_manager.cpp, foo_ui_columns/tab_fonts.cpp
This:
- updates the Columns UI SDK
- updates the `fonts::manager_v3` implementation to match the latest iteration of the service declaration
- moves `font_mode_t` from the Columns UI SDK to here
=> Update fonts::manager_v3 implementation

CHANGELOG.md, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/font_manager_data.h
This adds some protection against trying to release `cui::basic_callback` service instances (that were registered for font changes) during shut down, if something manages to leak a `cui::callback_token` (or otherwise hold on to it until components are being unloaded).
=> Protect against font callback service release during shut down

CHANGELOG.md, foo_ui_columns/buttons_config_droptarget.cpp, foo_ui_columns/mw_drop_target.cpp, foo_ui_columns/mw_drop_target.h, foo_ui_columns/ng_playlist/ng_playlist_droptarget.cpp, foo_ui_columns/playlist_switcher_drop_target.cpp, foo_ui_columns/playlist_tabs_drop_target.cpp
This should fix a rare drag-and-drop crash when dropping items on certain parts of the main window (and probably also the playlist tabs on reviewing the code).
This was related to some incorrect usage of `m_DataObject` in the `IDropTarget::Drop` implementation in a `uih::ole::set_drop_description()` call (and somehow `m_DataObject` being empty at the same time).
I could not recall a reason for removing the drop description in the `IDropTarget::Drop` implementation. It was not being done consistently, so I've stopped doing it everywhere. (Additionally, there was an incorrect call to `IDropTargetHelper::DragLeave()`...
The second commit also makes an attempt to tidy up some of the IDropTarget implementations (mainly by returning early and reducing indentation everywhere...)
=> Fix rare drag-and-drop crash

CHANGELOG.md
This fixes a link with incorrect text in the 3.0.0-alpha.1 change log.
=> Correct link text in change log

docs/source/item-details/title-formatting.md
This corrects the maximum `font-weight` value from 900 to 999 in the docs for the Item details `$set_format()` title formatting function.
=> Correct Item details maximum $set_format() font weight in docs

CHANGELOG.md, foo_ui_columns/font_utils.cpp
This fixes a bug where incorrect font sizes were used in some parts of the UI for system icon and menu fonts on older versions of Windows, when using a system DPI setting of greater than 100%.
=> Fix incorrect system font size on pre-Windows 10

CHANGELOG.md, foo_ui_columns/foo_ui_columns.rc
Fixes #1073
This stops Visual Studio getting confused about the text encoding of `foo_ui_columns.rc` (and makes it consistently save it as UTF-8).
The solution is from https://developercommunity.visualstudio.com/t/visualstudio-v1590-resource-editor-using-utf-8-bom/384705#T-N796658.
=> Fix text encoding of resource file

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp
This re-enables tab-based columns playlist view group titles. (They were probably incorrectly disabled in 4093c516953ac7e9436e582fc255d16d671b40f2.)
=> Re-enable tab columns in playlist view group titles

CHANGELOG.md, foo_ui_columns/item_details_text.cpp
Resolves #1075
This updates fbh and amends the error handler logic used when parsing a font code in Item details to log a more user-friendly error when `$set_font()` is called with an invalid font family name.
=> Log nicer error when $set_font() used in Item details with bad font name

CHANGELOG.md, foo_ui_columns/buttons_command_picker.cpp, foo_ui_columns/dark_mode_dialog.cpp, foo_ui_columns/dark_mode_dialog.h
This fixes a bug where neither the ‘Change command...’ nor the ‘Add’ buttons worked in the Options dialogue for the Buttons toolbar.
=> Fix bug adding buttons or changing button commands

docs/source/item-details/title-formatting.md, docs/source/playlist-view/title-formatting.md
This:
- fixes an unescaped `<` character on the Item details title formatting page
- reorders the `$set_format()` examples on the Item details title formatting page
- removes a redundant leading `_` in `%playlist_name%` on the playlist view title formatting page
=> Make minor documentation improvements

CHANGELOG.md
This updates ui_helpers to pick up this workaround for a Windows bug:
> `IDWriteFont3` inexplicably has the same IID as `IDWriteFont2`, meaning that the `IDWriteFont3` interface can't be reliably queried for.
>
> Equivalent functionality from `IDWriteFontFamily1` is used to work around the problem.
=> Work around Windows 8.1 crash on Fonts preferences tab

CHANGELOG.md, foo_ui_columns/font_manager_v3.cpp
This corrects an assumption when creating DirectWrite text formats that if axis values are populated then the typographic font family name is also populated.
This assumption was incorrect on most versions of Windows 10 and older versions of Windows 11.
It now falls back to the weight-stretch-style font family name if the typographic font family name is missing and axis values are populated.
Additionally, a few other minor tweaks were made in `ui_helpers` (namely to handle simulated fonts correctly on the same Windows versions as above).
=> Fix incorrect font family use in DirectWrite panels on Windows 10

CHANGELOG.md, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/font_manager_data.h, foo_ui_columns/font_manager_v3.cpp, foo_ui_columns/system_appearance_manager.cpp, foo_ui_columns/tab_text_rendering.cpp
This:
- adds a new ’No anti-aliasing’ text rendering mode
- renames the previous ‘Automatic’ mode to ‘Automatic anti-aliasing’
- adds a new ‘Default’ mode that disables anti-aliasing automatically based on the system font smoothing setting
=> Allow disabling anti-aliasing for DirectWrite rendered text

CHANGELOG.md, foo_ui_columns/tab_text_rendering.cpp
This renames it to ‘GDI-compatible, no anti-aliasing’, as it now uses a GDI-compatible text layout.
=> Rename ‘No anti-aliasing’ text rendering mode

CHANGELOG.md, foo_ui_columns/user_interface_impl.cpp
This fixes a bug where, when 'Minimise to icon' is enabled, a taskbar entry incorrectly appeared when using the hide command (View/Hide or `/hide` on the command line) while foobar2000 is already hidden.
=> Fix taskbar entry appearing when using hide command while already hidden

CHANGELOG.md, foo_ui_columns/main_window.cpp, foo_ui_columns/main_window.h, foo_ui_columns/mw_wnd_proc.cpp
This:
- fixes a bug where the focus was not restored to the correct window when minimising and restoring the main window
- suppresses focus restoration logic when the window is being destroyed, as it's unneeded at that point and can trigger other side effects
- tidies up a few very old static variables
=> Improve focus restoration logic on window activation

CHANGELOG.md
This updates ui_helpers to pull in a workaround for DirectWrite not rendering trailing whitespace for right- and centre-aligned text.
This workaround applies only to single-line text as rendered in list views and the status bar and pane.
=> Work around DirectWrite not rendering trailing whitespace

CHANGELOG.md, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/font_manager_data.h, foo_ui_columns/migrate.cpp, foo_ui_columns/tab_text_rendering.cpp
The way the previous `cui::fonts::rendering_mode` variable was handled caused problems when downgrading Columns UI.
This switches to a new variable and makes things more robust.
The value stored in the old variable is automatically copied to the new variable on upgrade.
=> Migrate to new text rendering mode config variable

CHANGELOG.md, foo_ui_columns/main_window.cpp, foo_ui_columns/status_pane_msgproc.cpp
This change makes an error message appear when on start-up when using Windows 7 SP1 without the Platform Update. (Previously, a crash occurred at a later point.)
The Platform Update is required as it contains an updated version of DirectWrite.
=> Fix crash when using Windows 7 without Platform Update

CHANGELOG.md, foo_ui_columns/font_picker.cpp
This fixes a crash following an error listing available fonts on the Font tab of the Colour and fonts preferences page.
=> Fix crash following failure to list fonts on Fonts preferences tab

CHANGELOG.md, foo_ui_columns/filter.cpp, foo_ui_columns/filter.h, foo_ui_columns/item_properties.cpp, foo_ui_columns/item_properties.h, foo_ui_columns/list_view_panel.h, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/playlist_switcher_v2.cpp, foo_ui_columns/playlist_switcher_v2.h, foo_ui_columns/system_appearance_manager.cpp
This notifies all font changes of a font change whenever a font is installed or uninstalled in Windows.
This allows the UI to recover if a font in use is deleted or replaced.
Additionally, some list view text format creation logic was refactored.
=> Notify all font clients of font change on change to installed fonts

CHANGELOG.md, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details.h, foo_ui_columns/item_details_font.cpp, foo_ui_columns/pch.h
#954 
This migrates Item details from GDI to Direct2D. Text rendering appears to be identical in all modes.
This also adds support for SVG glyphs, in theory from later Windows 10 versions onwards (but I'm only aware of Windows 11 actually having SVG glyphs in Segoe UI Emoji).
Additionally, a couple of small bugs with padding and font-related title formatting fields were fixed.
=> Migrate Item details to Direct2D

CHANGELOG.md, foo_ui_columns/font_picker.cpp, foo_ui_columns/font_picker.h, foo_ui_columns/tab_fonts.cpp
This fixes a minor bug where the owner drawn combo boxes on the Fonts tab of the Colours and fonts preferences page incorrectly had a dark appearance in some cases on on foobar2000 1.x (which does not support dark mode for Preferences). This happened when Columns UI was the active UI and had dark mode enabled.
=> Fix dark mode handling on Fonts preferences tab on foobar2000 1.x

CHANGELOG.md, foo_ui_columns/main_window.cpp, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/system_tray.cpp, foo_ui_columns/system_tray.h, foo_ui_columns/system_tray_callbacks.cpp, foo_ui_columns/tab_system_tray.cpp, foo_ui_columns/user_interface_impl.cpp
This fixes a bug where the system tray icon did not have the correct title after minimising the main window if ‘Always show icon’ is turned off and ‘Minimise to icon’ is turned on.
=> Fix wrong system tray icon tooltip after minimising to the system tray

CHANGELOG.md, foo_ui_columns/item_details.cpp
Using `ScrollWindowEx()` in Item details doesn't make sense now that Item details is using Direct2D.
The entire client window is now redrawn when scrolling.
=> Remove use of ScrollWindowEx in Item details

CHANGELOG.md, foo_ui_columns/item_details.cpp
This fixes a problem where the `D2DERR_RECREATE_TARGET` error wasn't quite handled correctly in Items details. As the DirectWrite text layout can contain references to Direct2D brushes as effects, it also needs to be recreated following a `D2DERR_RECREATE_TARGET` error.
=> Fix Item details handling of graphics card driver reset

CHANGELOG.md, foo_ui_columns/font_manager_v3.cpp, foo_ui_columns/font_utils.cpp
This implements some updates to the font API, and applies custom font fallback automatically to text formats created via the API when ‘Use alternative emoji selection logic’ is enabled.
=> Implement updated font API with emoji custom font fallback support

CHANGELOG.md, foo_ui_columns/font_manager.cpp, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/font_manager_data.h, foo_ui_columns/font_manager_v3.cpp, foo_ui_columns/system_appearance_manager.cpp, foo_ui_columns/tab_fonts.cpp, foo_ui_columns/tab_text_rendering.cpp
This implements an updated `cui:fonts::manager_v3` interface, with new methods for retrieving rendering options and the font fallback object, and for registering callbacks relating to those.
It should be uncommon that these are needed, as rendering options and the font fallback object are available via `cui::fonts::font`, but these methods are added for completeness.
=> Add rendering options and font fallback methods to fonts::manager_v3

CHANGELOG.md
Resolves #1072
This updates ui_helpers and mmh to pick up a work around for list view header text not rendering on Wine.
See https://github.com/reupen/ui_helpers/pull/200 for more details.
=> Work around Wine header custom draw limitations

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist.cpp
This fixes a problem where, in a few scenarios, the playlist view header could be incorrectly positioned.
This happened, for example, when the playlist view was scrolled right and auto-sizing columns was turned on or items were removed from the playlist causing the vertical scroll bar to disappear.
Additionally, a problem where the playlist vertical scroll position was sometimes reset after showing or hiding columns via the header context menu was fixed.
=> Fix incorrect playlist view header positioning after certain actions

CHANGELOG.md, foo_ui_columns/font_manager_data.cpp, foo_ui_columns/font_manager_v3.cpp, foo_ui_columns/system_appearance_manager.cpp, foo_ui_columns/system_appearance_manager.h
This makes DirectWrite-rendered text switch to greyscale anti-aliasing when Windows indicates that font smoothing is enabled but ClearType is not.
=> Use greyscale anti-aliasing when ClearType is disabled

CHANGELOG.md, foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/playlist_tabs.h, foo_ui_columns/playlist_tabs_wndproc.cpp
This fixes a regression in version 2.0.0 where the `CS_DBLCLKS` class style on the Playlist tabs container window was removed, preventing double-clicking in empty space in the Playlist tabs from working (it previously created a new playlist).
A little bit of tidying up of some Playlist tabs code has also been done.
=> Fix double-clicking in empty space in Playlist tabs

CHANGELOG.md, foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/playlist_tabs.h, foo_ui_columns/playlist_tabs_wndproc.cpp, foo_ui_columns/tab_playlist_tabs.cpp
This fixes a problem where the state of the ‘Hide when a single playlist is open’ Playlist tabs option in Preferences was reversed.
It also makes a change to the Playlist tabs size limits so that if ‘Hide when a single playlist is open’ is turned on, a Playlist tabs panel without a child panel has a maximum height of 0 when the tabs are hidden due to there being only one playlist.
=> Fix reversed state of Playlist tabs auto-hide setting

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_decoder.cpp, foo_ui_columns/artwork_decoder.h, foo_ui_columns/artwork_helpers.cpp, foo_ui_columns/artwork_helpers.h, foo_ui_columns/artwork_reader.cpp, foo_ui_columns/artwork_reader.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/wic.cpp, foo_ui_columns/wic.h
Resolves #1215 
This:
- tidies up the existing asynchronous artwork reading code
- moves image decoding to a background thread
- migrates to using Direct2D for rendering, including resizing images
- improves handling of rapid tracked track changes
These changes aimed at improving performance and avoiding blocking the UI e.g. when changing selection in the playlist view. Large images, for example, can be slow to decode and previously were able to noticeably block the UI.
=> Migrate Artwork view to Direct2D and decode images asynchronously

vcpkg-ports/LICENCE, vcpkg-ports/cppwinrt/cppwinrt-config.cmake.in, vcpkg-ports/cppwinrt/portfile.cmake, vcpkg-ports/cppwinrt/usage, vcpkg-ports/cppwinrt/vcpkg.json, vcpkg.json
Resolves #1226
The May Windows SDK update (version 10.0.26100.4188) includes an update to the `cppwinrt` headers that breaks compatibility with Windows 7 (and also stops Columns UI from building as it tries to link against those functions not available on Windows 7).
This switches to installing `cppwinrt` via vcpkg and pinning it to version 2.0.230706.1, the last one compatible with Windows 7. This version was not available via vcpkg, so an overlay port had to be used.
=> Pin C++/WinRT headers to last version compatible with Windows 7

CHANGELOG.md, foo_ui_columns/artwork_decoder.cpp, foo_ui_columns/artwork_reader.cpp, foo_ui_columns/buttons.cpp, foo_ui_columns/buttons_button_image.cpp, foo_ui_columns/command_line.cpp, foo_ui_columns/config_vars.cpp, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/item_details.cpp, foo_ui_columns/item_details_text.cpp, foo_ui_columns/item_properties.cpp, foo_ui_columns/main_window.cpp, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/ng_playlist/ng_playlist_inline_edit.cpp, foo_ui_columns/splitter_utils.cpp, foo_ui_columns/splitter_utils.h, foo_ui_columns/status_pane.cpp, foo_ui_columns/system_appearance_manager.cpp, foo_ui_columns/tab_layout.cpp, foo_ui_columns/version.cpp, vcpkg-ports/foonathan-lexy/portfile.cmake, vcpkg-ports/foonathan-lexy/vcpkg.json, vcpkg.json
This:
- removes the `/source-charset:utf-8` compiler option and adds `/utf-8` in its place
- updates dependencies installed via vcpkg
`/utf-8` is equivalent to specifying both `/source-charset:utf-8` and `/execution-charset:utf-8`. It’s required by the new version of {fmt}, and is a significant improvement over the previous situation as it means normal (`const char`) string literals are now interpreted as being in UTF-8, and so a lot of the previous faff trying to use `char8_t` literals with incompatible things is no longer required.
=> Use /utf-8 compiler option and update dependencies

CHANGELOG.md, foo_ui_columns/artwork_decoder.cpp
Resolves #1231
Since #1221, if decoding an image failed for whatever reason, the previous image incorrectly remained in the Artwork view.
This corrects the behaviour and it now removes the previously displayed image (and displays nothing). Decoding errors are logged in the console as before.
=> Don't show stale image in artwork view on decoding failure

CHANGELOG.md
This updates ui_helpers to bring in some list view performance improvements when reordering items.
The improvements mainly apply when grouping is turned off (as optimisations are easier to make when grouping is not used).
=> Improve playlist view performance when reordering items

CHANGELOG.md, foo_ui_columns/mw_wnd_proc.cpp
This adds detection of the keyboard focus being stolen by a panel when the main window first initialises. If that is detected, a playlist view is focused and a console message is emitted.
=> Work around stolen keyboard focus during main window creation

CHANGELOG.md, foo_ui_columns/artwork_reader.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/pch.h, foo_ui_columns/system_appearance_manager.cpp
Previously, changes to per-monitor ClearType settings made using the ClearType Text Tuner usually didn’t take effect until restarting foobar2000, or after changing Columns UI font settings.
Unfortunately, there is no official way to subscribe for notifications about changes to these settings. However, monitoring the relevant registry keys works. This adds a simple registry monitoring solution that works well enough.
Additionally, this sets thread descriptions for the Artwork view and playlist view artwork reader worker threads using the `SetThreadDescription()` function available on recent versions of Windows.
(`mmh::set_thread_description()` is used here, though `pfc::setCurrentThreadDescription()` is also available…)
=> Monitor per-monitor ClearType settings for changes

CHANGELOG.md, foo_ui_columns/artwork_reader.cpp, foo_ui_columns/artwork_reader.h
This fixes a crash that happened when the Artwork view was closed while it was reading artwork.
This occurred because the destruction order of `ArtworkReader` members meant some members the background thread depended on were destructed before the thread was joined.
=> Fix crash when Artwork view is destroyed while reading artwork

foo_ui_columns/pch.h
Unfortunately, the fix for #1226 is not working with Clang, as it still seems to using the C++/WinRT headers from the Windows SDK, rather than the ones installed via vcpkg.
This change links `windowsapp.lib` when compiling with Clang to at least fix the linker errors.
=> Link windowsapp.lib when compiling with Clang

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork_reader.cpp, foo_ui_columns/d3d.cpp, foo_ui_columns/d3d.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/gdi.cpp, foo_ui_columns/gdi.h, foo_ui_columns/imaging.cpp, foo_ui_columns/imaging.h, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.h, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp
This migrates playlist view artwork scaling and reflection rendering from GDI+ to Direct2D.
A memory bitmap is still used and the prerendered image is still converted to a GDI bitmap. However, the GDI bitmap now uses premultiplied alpha and is alpha blended on to the GDI device context.
Additionally, a problem where artwork images in the playlist view varied in width by up to two pixels was also fixed.
Also, in some cases, the transparency gradient in reflections is slightly different now. As far as I can determine, the new behaviour is correct.
A few other small optimisations are also included.
=> Use Direct2D to prerender playlist view artwork

CHANGELOG.md, foo_ui_columns/artwork.cpp
This fixes a regression in #1275 where the interpolation mode for image scaling was not set correctly in the artwork view.
=> Correct scaling interpolation mode in artwork view

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_decoder.cpp, foo_ui_columns/artwork_decoder.h, foo_ui_columns/config_artwork.cpp, foo_ui_columns/d2d_utils.cpp, foo_ui_columns/d2d_utils.h, foo_ui_columns/foo_ui_columns.rc, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/resource.h
#1216
This adds support for basic (legacy) colour management to the artwork view.
This is now the default, as it works on all supported versions of Windows, and Advanced Colour requires the flip model for the DXGI swap chain which causes artefacts when resizing the artwork view.
Advanced Colour can be enabled in Preferences on Windows 10 1809 and newer. Note that, when enabled, colours can render differently for SDR displays. It probably shouldn't be used unless HDR is enabled in Windows. Legacy colour management renders colours identically to Chrome, Edge and Firefox (with [full colour management enabled in Firefox](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/3.5/ICC_color_correction_in_Firefox#configuring_color_correction)) for the SDR images I checked.
=> Add support for legacy colour management to artwork view

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/d2d_utils.cpp, foo_ui_columns/d2d_utils.h, foo_ui_columns/d3d_utils.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/pch.h
Resolves #1216
This makes a few small tweaks to Direct2D usage in the artwork and playlist views. It:
- adds and makes use of a few shared utility functions
- makes the effect pipelines in the playlist view more consistent with the one in the artwork view
- fixes handling of display changes in the artwork view
- stops automatically enabling Direct2D and Direct3D debug layers in debug builds (due to them having unwanted side effects, perhaps because they tend to be older versions than the main binaries)
=> Tweak Direct2D image handling

CHANGELOG.md, foo_ui_columns/main_window.cpp, foo_ui_columns/main_window.h, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/user_interface_impl.cpp
Resolves #1280
This resolves a problem where the focus was not restored to the relevant child window after performing a ReplayGain scan and applying changes.
=> Fix focus restoration after ReplayGain scan

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h
Fixes #1295
The scale effect was being updated before the Direct2D device context size was updated, so the updated scale was being based on the old render target size.
This delays updating the scale effect under rendering to avoid the problem.
=> Fix incorrect image size after resizing artwork view

CHANGELOG.md, foo_ui_columns/buttons.cpp, foo_ui_columns/buttons.h, foo_ui_columns/buttons_button.cpp
Resolves #1283
This adds support for making use of main menu command checked and disabled statuses in the buttons toolbar when the relevant `mainmenu_commands` service has implemented `mainmenu_commands_v3`.
Checked commands are displayed as pressed.
If both `uie::button` and `mainmenu_commands_v3` are implemented, `uie::button` is used in preference to `mainmenu_commands_v3`.
(I haven’t found any built-in commands in foobar2000 where this makes a difference so far, as some were already covered by `uie::button` implementations in Columns UI.)
=> Add support for mainmenu_command_v3 command state in buttons toolbar

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/d2d_utils.cpp, foo_ui_columns/d3d_utils.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp
I noticed on my system that the switch from `ID2D1HwndRenderTarget` to `ID3D11Device` and `ID2D1Device` was causing increased power consumption.
This was difficult to observe with monitoring software, but was easily seen with a plug-in energy monitor.
Even with `ID2D1HwndRenderTarget`, though, the higher power consumption level (around 7 to 8 watts higher) started once an image was rendered in the artwork view (and until foobar2000 was minimised). This seemed to be related to the CPU spending less time in low power states.
As it turned out, the root cause of these problems was that I had a global frame rate limit configured in the NVIDIA app, and it somehow triggers this higher power consumption. Removing that limit gets rid of the problem. Renaming `foobar2000.exe` to `explorer.exe` …
=> Adjust Direct3D/2D threading options

CHANGELOG.md, foo_ui_columns/artwork_decoder.cpp, foo_ui_columns/artwork_decoder.h
In MSVC, `std::async()` uses a thread pool. I’ve encountered (just once...) artwork stop loading due to COM initialisation failing in the async task. Presumably, this was due to something initialising COM as apartment-threaded (while in another `std::async()` task) and not deinitialising COM afterwards, and the thread then returning to thread pool like that.
This switches to using a temporary thread via `std::jthread`, so at least the thread state is always clean and that problem can't happen.
(Additionally, the thread priority is now `THREAD_PRIORITY_BELOW_NORMAL` like other background threads in Columns UI.)
=> Use std::jthread instead of std::async() in Artwork view

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_reader.cpp, foo_ui_columns/artwork_reader.h, foo_ui_columns/config_artwork.cpp
Resolves #1096
This adds a ‘Show in File Explorer’ command to the Artwork view, both in the context menu and as a click action. (The click action is configured in Preferences.)
=> Add ‘Show in File Explorer’ command to Artwork view

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_reader.h, foo_ui_columns/pch.h
This adds a dedicated context menu when right-clicking on the Artwork view. (Previously, the parent splitter’s context menu was shown with Artwork view items appended). 
This is as it was starting to get cluttered, and for consistency with other built-in non-toolbar panels.
Additionally, some related code was refactored, toggling the ‘Lock artwork type’ behaves better, and the logic relating to showing the stub image was improved so that it shows after certain actions or events that were previously not handled.
=> Add dedicated context menu to Artwork view

CHANGELOG.md, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/playlist_tabs.cpp, foo_ui_columns/playlist_tabs.h, foo_ui_columns/playlist_tabs_wndproc.cpp, foo_ui_columns/rebar.cpp, foo_ui_columns/rebar.h, foo_ui_columns/rebar_band.h, foo_ui_columns/splitter.h, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/splitter_tabs.h, foo_ui_columns/splitter_window.cpp, foo_ui_columns/splitter_window_wndproc.cpp
This fixes a long-standing bug where, if a single-instance panel was inserted in a built-in splitter twice, a crash would tend to occur.
Normally inserting a single-instance panel in the same splitter twice is not allowed, but it was (and potentially still is) possible via live editing. (Some improvements to live editing will also follow separately.)
These changes also improve handling of removing the active tab in a Tab stack panel during live editing. It now switches to another tab (if there is one), rather than leaving the Tab stack in a state where no tab is active. Internal logic for tracking the active tab was also changed to support these changes.
=> Fix handling of duplicate single-instance panels in built-in splitters

CHANGELOG.md, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/layout.cpp, foo_ui_columns/panel_utils.h, foo_ui_columns/tab_layout.cpp
This makes some improvements to live editing, primarily for single-instance panels.
It: 
- migrates the live editing context menu generation code to `uih::Menu`
- fixes a problem where, when right-clicking on a splitter, the supported panel list for its parent was used to populate the ‘Add panel’ submenu
- adds explicit logic to stop the same single-instance being added to the same parent more than once
=> Improve handling of single-instance panels during live editing

CHANGELOG.md, foo_ui_columns/splitter_tabs.cpp
This fixes a bug introduced in 55d74529c14a277880de88a8d6788abc6d912527 where an empty Tab stack panel crashed when the Tab stack window was shown.
=> Fix empty Tab stack crash

CHANGELOG.md, foo_ui_columns/layout.cpp, foo_ui_columns/layout.h, foo_ui_columns/layout_config.cpp, foo_ui_columns/splitter_tabs.cpp, foo_ui_columns/tab_layout.cpp
This contains a few improvements to the live editing context menu. It:
- refactors the code to use `uih::MenuCommandCollector` (replacing the previous horrible manual item ID logic)
- adds ’Move to/Previous position’ and ’Move to/Next position’ commands
- renames and reorders a few items, in line with recent changes to the layout tree context menu in Preferences
- fixes some bugs in the Tab stack `splitter_window::replace_panel()` implementation
The move-to commands aren’t labelled Move up and Move down like in the layout tree, as that doesn't make sense in this context (where they could visually move left and right, or in some other order depending on the splitter).
The move-to commands still need some further improvement, as the double panel replacement it currently uses doesn't work so …
=> Add move commands to and tweak menu item labels and order in live editing context menu

CHANGELOG.md, foo_ui_columns/menu_items.cpp
For some reason the the active preset menu item in the View/Layout menu was using `mainmenu_commands::flag_checked` rather than `mainmenu_commands::flag_radiochecked`, and hence the wrong symbol was being shown.
This corrects that.
=> Correct active preset symbol in View/Layout menu

CHANGELOG.md, foo_ui_columns/foo_ui_columns.rc, foo_ui_columns/layout.cpp, foo_ui_columns/mw_wnd_proc.cpp, foo_ui_columns/panel_utils.h, foo_ui_columns/splitter.cpp, foo_ui_columns/tab_layout.cpp
Resolves #358
This:
- rename ‘Splitters’ panel category to ‘Containers’, to better reflect the types of panels that sit in the category
- renames ‘Horizontal splitter’ and ‘Vertical splitter’ to ‘Row’ and ‘Column’ respectively, to get rid of the confusion associated with the previous names
=> Rename ‘Splitters’ panel category and flat splitter panel names

CHANGELOG.md, foo_ui_columns/splitter.h, foo_ui_columns/splitter_tabs.cpp
This disables captions by default when adding panels to a row or column.
It also changes the Tab stack copy panel behaviour to stop it automatically enabling captions and make it set the panel size to 150 (the default value used in rows and columns), rather than 0.
=> Disable captions by default in rows and columns

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/ng_playlist/ng_playlist_renderer.cpp
Enabling artwork relections in the playlist view caused narrow images to render incorrectly, because it was scaling the image too large as it wasn't correctly accounting for the additional height of the reflection.
=> Fix playlist view artwork relections for narrow images

CHANGELOG.md, foo_ui_columns/artwork.cpp, foo_ui_columns/artwork.h, foo_ui_columns/artwork_reader.cpp, foo_ui_columns/artwork_reader.h, foo_ui_columns/fb2k_callbacks.cpp, foo_ui_columns/fb2k_callbacks.h, foo_ui_columns/foo_ui_columns.vcxproj, foo_ui_columns/foo_ui_columns.vcxproj.filters, foo_ui_columns/ng_playlist/ng_playlist.cpp, foo_ui_columns/ng_playlist/ng_playlist.h, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.h, foo_ui_columns/ng_playlist/ng_playlist_callbacks.cpp, foo_ui_columns/ng_playlist/ng_playlist_groups.h
This:
- updates the playlist view to invalidate artwork for a group if the first track in the group is modified
- updates the Artwork view reload artwork if it’s showing art for a selection and the first track in that selection is modified
- fixes a bug where the Artwork view didn't update if it was showing artwork obtained via `now_playing_album_art_notify_manager`, and then that artwork was removed (e.g. an embedded front cover was removed from the track)
For the first two changes, it is only the first track (of the group or the selection) that is considered, because that is the track that artwork is shown for.
These changes help to make changes to embedded artwork immediately visible, and also to update shown artwork where changes to metadata affect the external artwork search (without …
=> Reload artwork when the source track is modified

CHANGELOG.md, foo_ui_columns/ng_playlist/ng_playlist.cpp
This fixes a bug in the foobar2000 2.0 and newer code path for sorting by a column, where it did not handle the stripping of colour codes from strings correctly, causing sorting to behave unexpectedly.
=> Fix sorting by playlist view column containing colour codes

CHANGELOG.md, foo_ui_columns/foo_ui_columns.rc, foo_ui_columns/tab_setup.cpp
The solution for changing the dark mode link colour wasn’t working on foobar2000 2.24. This fixes that by updating `fbh` to make the subclassing happen earlier. The link was also moved down further from the heading above it.
This also fixes a bug where other controls on the tab triggered a crash, due to a missing `break` under `WM_COMMAND`.
=> Fix documentation link-related Setup preferences tab problems

CHANGELOG.md, foo_ui_columns/filter_search_bar.cpp, foo_ui_columns/font_picker.cpp, foo_ui_columns/ng_playlist/ng_playlist_prefs_groups.cpp
Resolves #1368
This adds edit control enhancements that add support for Ctrl+Backspace, and support for Ctrl+A on old versions of Windows, to Filter search, and a couple of edit controls in Preferences that had previously been missed.
=> Add edit control enhancements to Filter search and some edit controls

CHANGELOG.md
This updates ui_helpers. The update fixes a minor bug where the PgUp and PgDn keys did not do anything in list views for very small window heights (particularly if grouping was enabled).
=> Fix list view PgUp and PgDn handling for very small heights

CHANGELOG.md, foo_ui_columns/dark_mode.cpp
The colour of the ‘Columns UI documentation site’ hyperlink on the Setup tab in Preferences was noticeably wrong on Windows 7. On further investigation, the correct colour to use is `COLOR_HOTLIGHT`. (The colour was slightly off for light mode on Windows 10 and 11 as well, but not noticeably so.)
=> Correct light mode colour of documentation site link

CHANGELOG.md, foo_ui_columns/artwork_decoder.cpp, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/wic.cpp, foo_ui_columns/wic.h
This resolves a problem were some CMYK and high-bit-depth greyscale images did not render correctly.
It seems like `WICConvertBitmapSource`/`IWICFormatConverter` converts these to sRGB automatically (at least, I was unable to see any noticeable difference from doing a manual conversion).
Doing an explicit conversion to sRGB is also a bit of a pain as it can fail in cases, so this change works on the assumption that `IWICFormatConverter` is doing it.
=> Fix rendering of some non-RGB images

foo_ui_columns/artwork_decoder.cpp, foo_ui_columns/imaging.cpp, foo_ui_columns/imaging.h, foo_ui_columns/ng_playlist/ng_playlist_artwork.cpp, foo_ui_columns/wcs.cpp, foo_ui_columns/wcs.h
#1389
This makes the Artwork view and playlist view not try to use a display colour profile again if creating a Direct2D colour context from it fails.
Additionally, a more user-friendly error message is now logged when creating a colour context from the display profile fails.
=> Don’t retry using display profiles if D2D rejects them
